### ISSUE TITLE
Inserting/moving node to become root node with 'first-child'/'last-child' 

### ISSUE THREAD

**Issue by nivertius** [django-mptt/django-mptt#136]
To mirror behavior with child nodes, inserting/moving node with 'first-child'/'last-child', it should be also possible to do it with target = None

    SomeModel.tree.move_node(obj, None, 'first-child')

This should move node as first root and position='last-child' should move it as last.

Currently, it is possible to insert/move node to be first root node with:

    first_node = SomeModel.tree.root_nodes()[0]
    SomeModel.tree.move_node(obj, first_node, 'left')

This should be also possible if node about to be moved (`obj`) is already a root node, without need to checkout first node from database.

Yes, the 'first-child' will be somehow misleading, because it won't be a 'child'. But it would accomplish something that user would expect. In contrast, currently moving node to become root passing target = None when it is already a root does nothing, instead of reordering nodes.

**Comment by matthiask** [comment]
We would gladly accept a pull request. Thanks in advance!
