### ISSUE TITLE
{% recursetree %} doesn't insert children context into template

### ISSUE THREAD

**Issue by dlo** [django-mptt/django-mptt#139]
I'm using the recursetree template tag. It fills the context with the node, but skips the children. Here's a snippet of my code:

```
{% recursetree areas %}
  <ul class='tree'>
    <a href='javascript:;' class='selected'>{{ node.long_name }} ({{ node.get_place_count }})</a>
      {{ children }}
  </ul>
{% endrecursetree %}
```

All that's being written to the template is:

```
<ul class='tree'>
<a href='javascript:;' class='selected'>United States (0)</a>

</ul>
```

**Comment by madhav-dhungana** [comment]
There is still same problem

**Comment by madhav-dhungana** [comment]
I am trying to call parent and child element of a model, I have gone through the MPTT model documentation. I did as mentioned on the documentation, but my template is failing to print children

What can be the possible cause of this problem?

Here is my Views:

    def category_view(request):
    category = Categories.objects.all()
    brands = Brands.objects.all()
    context ={
        'category':category,
        'brands':brands,
           
                
    }
    return render(request,'./ecommerce/categories.html', context)

and Here is my template HTML:

    {% load mptt_tags %}
         {% recursetree category%}
            <div class="category-wrap mb-4">
                <div class="category category-group-image br-sm">
                    <div class="category-content">
                        <h4 class="category-name"><a href="">{{ node.name }}</a>
                        </h4>
                        
                        <ul class="category-list">
                            {% if not node.is_leaf_node %}
                            <li><a href="">{{children}}</a></li>
                            {% endif %}
                           
                        </ul>
                        
                    </div>
                    
                </div>
            </div>
            
            
            {% endrecursetree %}

Parent element is printed but children element is not being printed

**Comment by madmax73** [comment]
Having the same problem,  {% recursetree category %} with {{children}}, does not display the children
