### ISSUE TITLE
'mptt_admin' is not a valid tag library: ImportError raised loading mptt.templatetags.mptt_admin: cannot import name result_hidden_fields

### ISSUE THREAD

**Issue by martcot** [django-mptt/django-mptt#162]
I got this error when I want to use admin classes. 'mptt_admin' is not a valid tag library: ImportError raised loading mptt.templatetags.mptt_admin: cannot import name result_hidden_fields

**Comment by biwin** [comment]
happens if `mptt` is not listed in `INSTALLED_APPS`

**Comment by muloh** [comment]
Found a clearer solution here https://www.wemakeitclear.com/en/blog/blog_details/8/mptt_tags-is-not-a-registered-tag-library-must-be-one-of
