### ISSUE TITLE
The initial tree building

### ISSUE THREAD

**Issue by svafn** [django-mptt/django-mptt#248]
Hi

Django 1.5.1
django-mutt 0.5.5

models.py

    from django.db import models
    from mptt.models import MPTTModel, TreeForeignKey

    class Genre(MPTTModel):
        name = models.CharField(max_length=50, unique=True)
        parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

        class MPTTMeta:
            order_insertion_by = ['name']
        

python manage.py shell

    from myapp.models import Genre
    rock = Genre.objects.create(name="Rock")
    blues = Genre.objects.create(name="Blues")
    Genre.objects.create(name="Hard Rock", parent=rock)
    Genre.objects.create(name="Pop Rock", parent=rock)
    Genre.objects.create(name="BLUES my", parent=blues)

Result:

    2 Blues 
        6 BLUES my 
        3 Hard Rock 
        4 Pop Rock 
    1 Rock

Genre.tree.rebuild()
Result:

    2 Blues 
        6 BLUES my 
    1 Rock 
        3 Hard Rock 
        4 Pop Rock
        
?

**Comment by rvanlaar** [comment]
What is the status on this issue? It still exists: Django 1.7.4, python2.7 and python 3.4

It is costing me a couple of hours now to just start using mptt and I'm still in the fase:
How can I be sure this tree thing is correct when the simple tutorial is still not working for me.

**Comment by craigds** [comment]
Tracking this at #320
