### ISSUE TITLE
How to properly bulk import?

### ISSUE THREAD

**Issue by rolodex** [django-mptt/django-mptt#277]
Hello,

I am importing my data from many sqlite databases in to my tree (about 7000 entries per db). First, I am creating a new branch in the tree (starting from the root, if necessary), and then I add all of my data from this sqlite database within one branch.

What I immediately noticed is that .save() takes forever once I started having multiple branches in my tree. So I searched around and found #201 which references #69 .

I looked at the docu for disable_mptt_updates and delay_mptt_updates. If I don't create a new branch starting from the root node, then I expect to need to use delay_mptt_updates. And so thats what I tried, and I can see that .save() takes no time, but once the code reaches the end of "with transaction.commit_on_success():", then CPU usage hits 100% and disk access doesnt seem to be very high, nonetheless, it takes a long time (about 10 minutes) when I only entered about 7000 new objects.

As I am writing this, I noticed that there are two versions of the documentation for this function (for version 0.6.0) one here:
http://django-mptt.github.io/django-mptt/mptt.managers.html
and one here
https://django-mptt.readthedocs.org/en/latest/mptt.managers.html

The first says to code:
> with transaction.commit_on_success():
>     with MyNode.objects.delay_mptt_updates():
>         ## bulk updates.

and the second:
> with transaction.atomic():
>     with MyNode.objects.delay_mptt_updates():
>         ## bulk updates.

Any tips how I can speed up bulk imports?

**Comment by lddubeau** [comment]
I'm using django-mptt 0.6.1 with Django 1.7, and ran into a few issues while trying to import about 240,000 records into a model that uses django-mptt. I landed on this issue report, which helped some but left a couple issues unsolved. You definitely want to use `.disable_mptt_updates()` and `.rebuild()` to speed things up.

1. One thing that can cause serious slowdown and high memory usage is running an import with the `DEBUG` setting set to `True`. This will cause Django to record all SQL queries for debugging purposes. With my 240,000 records it was enough to cause an out-of-memory crash. I prefer to leave debugging on in development, but to conserve memory, I added a periodic call to `django.db.reset_queries()`. This is not an mptt-specific issue but people are likely to trip on it if they import large datasets.

2. If you want to use `bulk_create()` you have to fill some of the fields that would be filled by mptt yourself.  I got errors until I added the following code:

            last.lft = 1
            last.rght = 1
            last.tree_id = last.parent.tree_id
            last.level = last.parent.level + 1

`last` is the object I want to save for later creation with `bulk_create()` and `last.parent` points to its parent. `lft` and `rght` are filled to obviously bunk values. They will be updated to real values when `.rebuild()` is called.

**Comment by matthiask** [comment]
What's the status of this issue? Is there a bug to be fixed or only a best practice to be documented?

(Assuming the later, therefore tagging as "documentation". Please revert if this is wrong.)

**Comment by lddubeau** [comment]
@matthiask I don't recall what it is exactly that two months ago was resolved for me by the earlier comments on this issue report.

Looking back at **my** own comment, what I mention there falls squarely into the realm of documentation.

**Comment by matthiask** [comment]
Pull request: https://github.com/django-mptt/django-mptt/pull/444. Work (if any) should continue there. Thanks.
