### ISSUE TITLE
Django mptt 0.6 - get_ancestors not working

### ISSUE THREAD

**Issue by pypetey** [django-mptt/django-mptt#285]
I am trying to create breadcrumbs for places.

country <- voivodeship <- county <- town

When I call self.get_ancestors(include_self=True) on town object I only get returned this particular object and I don't get other objects.

Calling - self.get_root - does not return anything

Calling self.parent_get_ancestors kinda works but my object is ignored and it's not in the tree like it supposed to work.

I did Place.objects.rebuild() but it did not help

   class Place(MPTTModel):

```
parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

# Location metadata
lng = models.FloatField(null=True, blank=True)
lat = models.FloatField(null=True, blank=True)
population = models.PositiveIntegerField(null=True, blank=True)
country_code = models.CharField(max_length=2, null=True, blank=True)

def __unicode__(self):
    return u"{}".format(self.name)

def get_absolute_url(self):
    return reverse("place:detail", kwargs={'pk': self.pk, 'location': self.slug, })

def get_tree(self):
    print get_ancestors(include_self=True)
    print self.get_root()
    return ""
```

**Comment by DylanYoung** [comment]
Not the same issue, but FYI It fails in Custom Managers that change the default filtering. 

Is there a recommended way of doing this?

**Comment by funkindy** [comment]
@matthiask Same here, get_ancestors with default filtering on custom manager fails (also selects children sometimes)
