### ISSUE TITLE
Fixtures can load, but error on delete - 'str' object has no attribute '_base_manager'

### ISSUE THREAD

**Issue by thongly** [django-mptt/django-mptt#305]
I have created a set of fixtures for my initial data via `manage.py dumpdata`. These fixtures even load properly, and I am aware of some past tickets where _loading_ fixtures seems to be the issue.

However, once loaded, I find that I cannot delete these instances, either in the admin or the shell.

This is contrary to the situation when the _exact_ same models were used to create the fixtures. When first inputting the data as models via the admin, the instances were created, and then could be deleted.

Any help would be appreciated.

**Comment by bbengfort** [comment]
Just a quick comment in case it will help others who are in this position: you can't use the typical "app.Model" approach when declaring a `GenericRelation` - you must import the model and use it directly. The `str` object that has no `_base_manager` is the string you used to define the Model towards the GenericRelation.

I had some code as follows:

```python
class Post(models.Model):
    ...
    category    = GenericRelation( 'categories.Category', related_query_name='posts' )
```
Thinking that it would work like any other foreign relation with the `app.Model` style. I was wrong. Importing the Category model directly from the categories app and then using it directly with GenericRelation fixed the problem:

```python
from categories import Category

class Post(models.Model):
    ...
    category    = GenericRelation( Category, related_query_name='posts' )
```

Probably this is a contenttypes bug that someone should report.

**Comment by arielnoname** [comment]
So, @thongly , what's the answer for this? I couldn't get it from stackoverflow's answer... I have the same, a "ratings" model pluggable to the Post and the Comment model, each one with:

ratings = GenericRelation('Rating', related_query_name='comments')

Can't delete the Post

**Comment by thongly** [comment]
TBH I forget exactly what I did, but I seem to remember that removing the `GenericRelation` was part of the solution.

**Comment by arielnoname** [comment]
yeah, that fixed it, thanks!
