### ISSUE TITLE
Breadth-first bulk ordered insertion results in broken tree

### ISSUE THREAD

**Issue by craigds** [django-mptt/django-mptt#320]
Workaround is to either insert in depth-first order, or run .objects.rebuild() after bulk insertion.

Reported by Antony Gelberg at  https://groups.google.com/forum/#!topic/django-mptt-dev/HKf9nDDqSY8

**Comment by craigds** [comment]
another report: http://stackoverflow.com/questions/27874094

**Comment by mauricioabreu** [comment]
I already had this issue a few months ago. I don't remember what I did wrong but to solve the problem I used rebuild method. It just happens after a bulk insert. Not sure if update goes wrong in this case. I don't think so...

**Comment by khorammfar** [comment]
this error still exists: `A node may not be made a child of any of its descendants.`

`rebuild()` method not working!

sometimes works but sometimes django give me this error.!
