### ISSUE TITLE
raw_id_field and MPTTModelAdmin are uncompatible

### ISSUE THREAD

**Issue by krasnoperov** [django-mptt/django-mptt#335]
It is not possible to use raw_id_fields together with MPTTModelAdmin.

Let's assume following model and admin:

    class Rubric(models.Model)
        parent = TreeForeignKey('self')

    class RubricAdmin(MPTTModelAdmin):
        raw_id_fields = ('parent', )

In Admin interface on Rubric Edit Page it is possible to open popup (by click on search icon near rubric raw_id field) and choose desired parent rubric. Normally, user clicks on name of selected item in popup and ID of that item appears in rubric field.

But actually nothing happens. Popup refreshed after click and that is all.

Reasons are simple. Item's link in popup must be like this:

    <a href="/admin/rubrics/rubric/1/?_changelist_filters=_popup%3D1%26_to_field%3Did" onclick="opener.dismissRelatedLookupPopup(window, '1'); return false;">item</a>

But actually '_changelist_filters' are missed:

    <a href="/admin/rubrics/rubric/1/" onclick="opener.dismissRelatedLookupPopup(window, 2'); return false;">item</a>

Any ideas how to fix it?

P.S. Version of Django is 1.7, django-mptt is 0.6.1 and master

**Comment by matthiask** [comment]
Cross-posting https://github.com/django/django/commit/534ced5aadf964eca4cf29a689dc70185f582772 here as well.
