### ISSUE TITLE
Draggable admin view

### ISSUE THREAD

**Issue by mazing** [django-mptt/django-mptt#336]
Are there any plans to implement a draggable admin view so the structure can be changed easier?

It seems there are multiple solutions based on mptt, but some of them are a bit outdated and I think it would be a great implementation to the original project.

**Comment by matthiask** [comment]
Thanks, @craigds. I haven't seen this one. I have been thinking about splitting FeinCMS into a tree editing component and a content editing component for quite some time now, but integrating a stripped down version of the TreeEditor into django-mptt sounds so much better to me. 

Of course I'd continue doing my part keeping the code up to date.

(Side note: django-treebeard already has a tree editing interface based on FeinCMS: https://tabo.pe/projects/django-treebeard/docs/2.0/admin.html#advanced-interface)

**Comment by matthiask** [comment]
@mazing Have look at https://github.com/django-mptt/django-mptt/pull/426 if you find the time!

**Comment by matthiask** [comment]
Fixed in https://github.com/django-mptt/django-mptt/commit/1041158647bb3c7ee84a3a0d6f04e65379f264de
