### ISSUE TITLE
Order insertion by a field with null value

### ISSUE THREAD

**Issue by mazing** [django-mptt/django-mptt#340]
If the a field `name` in `order_insertion_by = ['name']` is null it results in an error `Cannot use None as a query value mptt`.

Shouldn't it just ignore the null value and interpret it as blank?

**Comment by LeGast00n** [comment]
Just experienced the same issue.
I suppose the insertion_target_filters() method should use something like:
    q = Q(field_name + '__isnull'=True) | Q(**{field_name + filter_suffix: value})

**Comment by LeGast00n** [comment]
Here is a suggested fix:
    def insertion_target_filters(self, instance, order_insertion_by):
          ...
           # Existing portion of code
            if value is None:
                # node isn't saved yet. get the insertion value from pre_save.
                field = instance._meta.get_field(field_name)
                value = field.pre_save(instance, True)
            
            # Additional portion of code
            if value is None:
                value = bool(filter_suffix=='__lt')
                filter_suffix = '__isnull' 
            # END Additional portion of code
         ...

**Comment by olivierdalang** [comment]
I opened PR #547 to fix this. Let me know if I can do anything else to get this merged ;) Thanks for the great work !

**Comment by LeGast00n** [comment]
Hi there. I did that successfully some time ago and trying to remember. Reading this, I would say it transforms a condition from *__lt = None (as the case might arise if value is None) to *__isnull = True and *__gt = None to *__isnull = False. Now I don't remember the context of this fix but can only recommend to think of what *__lte is supposed to do in this context.
