### ISSUE TITLE
Has ancestor

### ISSUE THREAD

**Issue by mazing** [django-mptt/django-mptt#341]
I love django-mptt but I really miss an option to filter if an object has a node as ancestor.

Right now I can make a queryset with `Genre.objects.filter(parent=obj)` but it could be really useful if I could do something like `Genre.objects.filter(has_ancesor=obj)`.

I know I could do something like `filter(genre__in=obj.get_descendants(include_self=True))` but it will cost alot of memory. Couldn't it be done smarter?

**Comment by tubaman** [comment]
The custom filter would be useful when filtering in the admin.
