### ISSUE TITLE
list index out of range when using raw sql

### ISSUE THREAD

**Issue by 57even** [django-mptt/django-mptt#343]
When using raw sql `Group.objects.raw("SELECT * FROM group ORDER BY  tree_id ASC, lft ASC")` I get an error `list index out of range` when there are no objects in table `group`.

I check if the queryset is empty in the template before calling `recursetree` so I thought that the template tag `recursetree` would never be called when empty? If I replace my raw sql query with `Group.objects.all()` everything works as it should.

**Comment by craigds** [comment]
closing; if this is still a problem please reopen with more information.
