### ISSUE TITLE
Cannot reorder a query once a slice has been taken

### ISSUE THREAD

**Issue by 57even** [django-mptt/django-mptt#344]
Is it possible to avoid the error `Cannot reorder a query once a slice has been taken.`?

It's just comments which belongs to a specific post. So the queryset is `Comment.objects.filter(post=self.post)`. I think it's a pretty common use-case so I guess there already is a solution for this one :-)

**Comment by craigds** [comment]
#281 has been fixed so this has probably been fixed too.
