### ISSUE TITLE
Update fails when the model has a custom primary key

### ISSUE THREAD

**Issue by sergio-garcia** [django-mptt/django-mptt#363]
Today is not possible to update a model which uses a custom primary key if the field type is not an AutoField.

The following model reproduces the problem.

    from datetime import date
    from uuid import uuid4

    from django.db import models
    from mptt.models import MPTTModel, TreeForeignKey

    class Item(MPTTModel, models.Model):
        """
        Using bleeding edge django for UUIDField (any other field type will cause the same problem) and django-mptt
        pip install django==1.8b2
        pip install git+https://github.com/django-mptt/django-mptt.git@master

        >>> i=Item.objects.create(code='123',name='abc')
        >>> i.save()
        Traceback (most recent call last):
        ...
        ValueError: The following fields do not exist in this model or are m2m fields: id
        """
        id = models.UUIDField(primary_key=True, default=uuid4)
        code = models.CharField(max_length=20, verbose_name='code')
        name = models.CharField(max_length=50, verbose_name='name')
        parent = TreeForeignKey('self', blank=True, null=True, related_name='children', verbose_name='parent')

        def __str__(self):
            return self.code + ' - ' + self.name

        class MPTTMeta:
            order_insertion_by = ['code']

**Comment by craigds** [comment]
This implies you can't pass the custom PK to `Model.save(update_fields=['id'])` in Django 1.8?

Sounds like a bug in Django; I can't think of any reason why that would be the case.

Perhaps you could file this with Django?

**Comment by sergio-garcia** [comment]
The primary key should be immutable on updates. This is already addressed in django mptt for AutoField, see my pull request #364, it do the same for any field which is an PK.

**Comment by craigds** [comment]
Fair enough. Fixed via #364
