### ISSUE TITLE
UserWarning: cache_tree_children() was passed a queryset with the wrong ordering

### ISSUE THREAD

**Issue by Wtower** [django-mptt/django-mptt#365]
Just updated to 0.7.0. I get his warning:

UserWarning: cache_tree_children() was passed a queryset with the wrong ordering: ['tree_id', 'lft'].
This will cause an error in mptt 0.8.

I am trying to render a tree as in the template in the documentation tutorial. The only difference being that the context is parent.get_children().

I understand that https://github.com/django-mptt/django-mptt/issues/281 is related, but I haven't been able to figure this out.

Thanks.

**Comment by craigds** [comment]
Thanks for pointing this out. That's a big enough bug that it's going to
confuse a lot of people, so I've just pushed a fix
<https://github.com/django-mptt/django-mptt/commit/8187401d5377d188f6c319c79c421fc4d4f434c9>
and released it as 0.7.1.

Cheers
Craig de Stigter

**Comment by Wtower** [comment]
Thanks for the fix! The warning indeed went away. I am glad this helped.
