### ISSUE TITLE
Django 1.8 compatibility / manage.py shell not working

### ISSUE THREAD

**Issue by jtiri** [django-mptt/django-mptt#367]
I try run shell or shell_plus in django 1.8, but it not working. Runserver and runserver_plus working OK.
Error message:
  class DocumentObject(MPTTModel):
  File "/usr/local/lib/python2.7/site-packages/mptt/models.py", line 244, in __new__
    cls = meta.register(cls)
  File "/usr/local/lib/python2.7/site-packages/mptt/models.py", line 338, in register
    tree_manager.init_from_model(cls)
  File "/usr/local/lib/python2.7/site-packages/mptt/managers.py", line 52, in init_from_model
    [tree_field] = [fld for fld in model._meta.get_fields_with_model() if fld[0].name == self.tree_id_attr]
...
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

**Comment by tangent** [comment]
this problem has been fixed already in release .7, update to the latest version on PyPI

**Comment by jtiri** [comment]
Not working. I unistall and reinstall django-mptt packages.
Version: django-mptt==0.7.1

**Comment by datakid** [comment]
@jtiri This is a common error in upgrading from Django <1.7 to Django =>1.7, not necessarily related to MPTT.

If you google the error " django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet." there are lots of results - you may need to make small adjustments to your settings or wsgi file?

**Comment by craigds** [comment]
sounds like you're not really using 0.7.1 - that line was removed in 9fc198c0ccd0365d0412389562bd62b85e4161e9 . Maybe something wrong with a virtualenv, or ...?

**Comment by datakid** [comment]
One solution would be to uninstall django-mptt, then cdsitepackages, then confirm it's uninstalled (ie, list dir, if it's there, rm -rf django-mptt) then reinstall
