### ISSUE TITLE
Using cls.__dict__ sometimes returns <class 'django.db.models.manager.ManagerDescriptor'>

### ISSUE THREAD

**Issue by benjaoming** [django-mptt/django-mptt#369]
I'm having problems that I didn't get to the bottom of, except that reverting back to `getattr` instead of accessing via `__dict__` is the remedy.

Problem was that a custom manager was not set, and we were defaulting back to TreeManager.

The culprit was this:

                            # HACK: avoid using getattr(cls, attr)
                            # because it calls __get__ on descriptors, which can cause nasty side effects
                            # with more inconsiderate apps.
                            # (e.g. django-tagging's TagField is a descriptor which can do db queries on getattr)
                            # ( ref: http://stackoverflow.com/questions/27790344 )
                            obj = cls.__dict__[attr]

It was causing django-wiki/django-wiki#404

PR coming in......

**Comment by benjaoming** [comment]
Here's the exact cause: a01b157ed15d412c664f31b5c0d3b4f3eddc0937

But I realize it fixes another important issue.

**Comment by craigds** [comment]
Hi Ben

The last comment on the django-wiki ticket implies this is something to do with `.none()` querysets, but I'm not quite sure how that relates to `ManagerDescriptor`.

Perhaps you could you clarify a bit?

**Comment by benjaoming** [comment]
@craigds thanks for getting back

I had to halt the investigation, but I'm trying to figure it out. I was building a test case for django-mptt but it somehow succeeds (oh no!!! `type(Model.objects.all()[0].get_children()) is CustomQuerySet`) with the current codebase, but the *exact* same thing in django-wiki is failing with the same structure (`type(Model.objects.all()[0].get_children()) is TreeQuerySet` instead of `CustomQuerySet`).

Human rant: So the problem caused by the way that django-wiki's custom manager... something isn't playing the right way, since it's returning a `ManagerDescriptor` (that's a class that will just raise an exception about not using manager functions directly on an object), and then django-mptt defaults to TreeManager because it doesn't find the custom manager inheriting from TreeManager.

**Comment by benjaoming** [comment]
Btw thanks for a great project again!!!

**Comment by benjaoming** [comment]
Okay I've found the problem, it's essentially this:

```python
class MyModel(MPTTModel):
    objects = MyCustomManager()
    _default_manager = objects  # <- THAT IS THE PROBLEM
```

**Comment by benjaoming** [comment]
...now I just need to figure out why that line was introduced

**Comment by benjaoming** [comment]
Confirming that django-wiki is working after commenting out the `_default_manager = objects` line.

**Comment by benjaoming** [comment]
Also confirming that I can make the django-mptt tests break by introducing this line... wondering if it's relevant since googling stuff about this issue reveals issues about older django versions.

**Comment by benjaoming** [comment]
Okay, it's all in #370 

I would add that it seems removing `_default_manager` in the model in django-wiki isn't harmful, I'll try it out and report back.

**Comment by benjaoming** [comment]
Argh, dammit, I wanted Travis to be showing off how the tests were failing in 2b47ffd and then how they are now working in 92737e9
