### ISSUE TITLE
Django 1.4 issue with .none() on custom queryset

### ISSUE THREAD

**Issue by benjaoming** [django-mptt/django-mptt#371]
Following lines have been uncommented for tests in #370 

        # This test is failing on Django 1.4, needs a decision
        # self.assertTrue(isinstance(Person.objects.all()[0].get_children().none(), CustomTreeQueryset))

**Comment by craigds** [comment]
Correct me if I'm wrong but afaict this was addressed in #372?

**Comment by benjaoming** [comment]
I had to comment out the test to get it running on 1.4 so it remains so until this issue is resolved :)

But you can just enable the line, and you'll get the test failure on 1.4.

**Comment by benjaoming** [comment]
https://github.com/django-mptt/django-mptt/pull/372/files#diff-fac85e7dd7822df3b1bb3edc1f1f963dR1246

**Comment by craigds** [comment]
Closing this as we abandoned django 1.4 support a while back
