### ISSUE TITLE
Django 1.8.1 + MPTT 0.7.3 conflicting models

### ISSUE THREAD

**Issue by murdav** [django-mptt/django-mptt#377]
When I launch the runserver I have this error:

Exception Type: RuntimeError
Exception Value:
```javascript
Conflicting 'topiccategory' models in application 'base': <class 'base.models.TopicCategory'> and <class 'fm.base.models.TopicCategory'>.
```
Somehow related to
https://code.djangoproject.com/ticket/23621
https://code.djangoproject.com/ticket/22280

	# settings/base.py
	INSTALLED_APPS = (
	    # Django
	    'django.contrib.admin',
	    'django.contrib.auth',
	    'django.contrib.contenttypes',
	    'django.contrib.sessions',
	    'django.contrib.messages',
	    'django.contrib.staticfiles',
	    'django.contrib.sites',
	    'django.contrib.gis',
	
	    # Assorted 3rd party
	    'mptt',
	    'compressor',
	    'clear_cache',
	    
	    'base',
	    *** others ****

	# base/base.py
	class TopicCategory(MPTTModel):
	    """
	    """
	    name = models.CharField(max_length=200)
	    slug = models.SlugField()
	    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')
	    description = models.TextField(blank=True)

In django/apps/registry.py line 210

        if model_name in app_models:
            if (model.__name__ == app_models[model_name].__name__ and
                    model.__module__ == app_models[model_name].__module__):
                warnings.warn(
                    "Model '%s.%s' was already registered. "
                    "Reloading models is not advised as it can lead to inconsistencies, "
                    "most notably with related models." % (model_name, app_label),
                    RuntimeWarning, stacklevel=2)
            else:
                raise RuntimeError(
                    "Conflicting '%s' models in application '%s': %s and %s." %
                    (model_name, app_label, app_models[model_name], model))

Errors are within 
```javascript
app_models[model_name].__name__ and app_models[model_name].__module__
```
__get_items__ takes exactly 1 argument (0 given)

Ideas?

**Comment by craigds** [comment]
I'm not sure I 100% grok this, but this:

```javascript
Conflicting 'topiccategory' models in application 'base': <class 'base.models.TopicCategory'> and <class 'fm.base.models.TopicCategory'>.
```

... sounds like perhaps both 'fm' (project?) and 'base' are on the pythonpath, and the model is getting imported from both paths. Seen several bugs like that before. Though I still haven't really got to grips with all the model loading changes in 1.7/1.8, so perhaps that's not something that happens any more.

Seems unlikely to be related specifically to django-mptt. Is this a new behaviour with mptt 0.7.x, or does it happen with 0.6.x too?

**Comment by murdav** [comment]
Thanks for replying. You are right (of course!), it's something related to Django itself.

I had to change all relative imports.
E.g. from .models import <ModelName> to from apps.application1.models import <ModelName>.
Nothing related to MPTT.
