### ISSUE TITLE
Issue with "get_queryset_ancestors"

### ISSUE THREAD

**Issue by p-clem** [django-mptt/django-mptt#379]
I'm having a weird issue with the get_queryset_ancestors method from the TreeManager.

I have a Category model wich inherits from MPTTModel

I have a certain amount of categories with 2 main parent categories (Men/Women)
```
>>> Category.objects.all() 
[<Category: Men>, <Category: Accessories>, <Category: Bags>, <Category: Bottoms>, <Category: Eyewear>, <Category: Footwear>, <Category: Jewelry>, <Category: Other>, <Category: Outerwear>, <Category: Sleepwear>, <Category: Sportswear>, <Category: Suits>, <Categor
y: Swimwear>, <Category: Tops>, <Category: Underwear & Socks>, <Category: Watches>, <Category: Women>, <Category: Accessories>, <Category: Bags>, <Category: Bottoms>, '...(remaining elements truncated)...']
```
So far so good.

This should return exactly the same queryset...
```
>>> Category.objects.get_queryset_ancestors(Category.objects.all(), include_self=True)  
[<Category: Men>, <Category: Women>]
```
But it doesn't...It's just as if  would ignore the include self.

But it even becomes trickier:

This works:
```
>>> Category.objects.get_queryset_ancestors(Category.objects.filter(pk__in=[3,]), include_self=True)  
[<Category: Men>, <Category: Accessories>]
>>> Category.objects.get_queryset_ancestors(Category.objects.filter(pk__in=[5,]), include_self=True)
[<Category: Men>, <Category: Bags>]
```
But then:
```
>>> Category.objects.get_queryset_ancestors(Category.objects.filter(pk__in=[3,5]), include_self=True)
[<Category: Men>]
```

django==1.7.5
django_mptt==0.7.3

**Comment by craigds** [comment]
That's pretty crazy. Can you post the output of 

    mptt.utils.print_debug_info(Category.objects.all())

and

    print(Category.objects.get_queryset_ancestors(Category.objects.all(), include_self=True).query)

**Comment by craigds** [comment]
Ah, I see what's going on. Looks like this was introduced here: 5ce827143818450a77d7bf9218760363f560969b

**Comment by p-clem** [comment]
```
>>> mptt.utils.print_debug_info(Category.objects.all())
pk,mptt_level,parent_id,tree_id,lft,rght,pretty
1,0,,1,1,32,Men
3,1,1,1,2,3,- Accessories
5,1,1,1,4,5,- Bags
7,1,1,1,6,7,- Bottoms
10,1,1,1,8,9,- Eyewear
12,1,1,1,10,11,- Footwear
15,1,1,1,12,13,- Jewelry
27,1,1,1,14,15,- Other
17,1,1,1,16,17,- Outerwear
31,1,1,1,18,19,- Sleepwear
29,1,1,1,20,21,- Sportswear
33,1,1,1,22,23,- Suits
20,1,1,1,24,25,- Swimwear
22,1,1,1,26,27,- Tops
24,1,1,1,28,29,- Underwear & Socks
25,1,1,1,30,31,- Watches
2,0,,2,1,38,Women
4,1,2,2,2,3,- Accessories
6,1,2,2,4,5,- Bags
8,1,2,2,6,7,- Bottoms
9,1,2,2,8,9,- Dresses
11,1,2,2,10,11,- Eyewear
13,1,2,2,12,13,- Footwear
14,1,2,2,14,15,- Intimates
16,1,2,2,16,17,- Jewelry
28,1,2,2,18,19,- Other
18,1,2,2,20,21,- Outerwear
32,1,2,2,22,23,- Sleepwear
19,1,2,2,24,25,- Socks
30,1,2,2,26,27,- Sportswear
34,1,2,2,28,29,- Suits
21,1,2,2,30,31,- Swimwear
23,1,2,2,32,33,- Tops
35,1,2,2,34,35,- Two-Pieces
26,1,2,2,36,37,- Watches
>>> print(Category.objects.all().get_ancestors(include_self=True).query)
SELECT "products_category"."id", "products_category"."name", "products_category"."slug", "products_category"."parent_id", "products_category"."url", "products_category"."lft", "products_category"."rght", "products_category"."tree_id", "products_category"."mptt_l
evel" FROM "products_category" WHERE (("products_category"."lft" <= 2 AND "products_category"."rght" >= 31 AND "products_category"."tree_id" = 1) OR ("products_category"."lft" <= 1 AND "products_category"."rght" >= 32 AND "products_category"."tree_id" = 1) OR ("
products_category"."lft" <= 2 AND "products_category"."rght" >= 37 AND "products_category"."tree_id" = 2) OR ("products_category"."lft" <= 1 AND "products_category"."rght" >= 38 AND "products_category"."tree_id" = 2)) ORDER BY "products_category"."tree_id" ASC,
"products_category"."lft" ASC
```

**Comment by musashiXXX** [comment]
Totally my fault.

I see where the problem is. Unfortunately I'm out of town so it'll take some time to fix. Here's a summary:

`get_queryset_ancestors` uses the left and right values of contiguous nodes to create the query. This reduces the number of variables that end up in the query which can increase performance and reduce the chance of getting an errors due to "too many variables". Here's an example that recreates the problem; it uses `myapp` from the django-mptt unit tests:

    >>>mptt.utils.print_debug_info(Category.objects.all())
    pk,level,parent_id,tree_id,lft,rght,pretty
    1,0,,1,1,20,PC & Video Games
    2,1,1,1,2,7,- Nintendo Wii
    3,2,2,1,3,4,- - Games
    4,2,2,1,5,6,- - Hardware & Accessories
    5,1,1,1,8,13,- Xbox 360
    6,2,5,1,9,10,- - Games
    7,2,5,1,11,12,- - Hardware & Accessories
    8,1,1,1,14,19,- PlayStation 3
    9,2,8,1,15,16,- - Games
    10,2,8,1,17,18,- - Hardware & Accessories

    >>> print(Category.objects.get_queryset_ancestors(Category.objects.filter(Q(pk=10)|Q(pk=7)), include_self = True).query)
    SELECT "myapp_category"."id", "myapp_category"."name", "myapp_category"."parent_id", "myapp_category"."category_uuid", "myapp_category"."lft", "myapp_category"."rght", "myapp_category"."tree_id", "myapp_category"."level" FROM "myapp_category" WHERE (("myapp_category"."lft" <= 11 AND "myapp_category"."rght" >= 12 AND "myapp_category"."tree_id" = 1) OR ("myapp_category"."lft" <= 17 AND "myapp_category"."rght" >= 18 AND "myapp_category"."tree_id" = 1)) ORDER BY "myapp_category"."tree_id" ASC, "myapp_category"."lft" ASC

In the example above, I've attempted to get the ancestors of a qureyset that contains two contiguous nodes:

    pk,level,parent_id,tree_id,lft,rght,pretty
    [...]
    9,2,8,1,15,16,- - Games
    10,2,8,1,17,18,- - Hardware & Accessories

This creates the following "range" selection:

    OR ("myapp_category"."lft" <= 15 AND "myapp_category"."rght" >= 18 AND "myapp_category"."tree_id" = 1)

So because neither of the nodes we're requesting the ancestors for fit the criteria, but their parent does, the two nodes do not appear in the results.

**Comment by musashiXXX** [comment]
@p-clem: Can you test `get_queryset_ancestors` and `get_queryset_descendants` using [this branch](https://github.com/musashiXXX/django-mptt)? My fix passes tests but:

1. I'd like to see if it fixes your problem and...
2. I'd like to clean it up a bit before initiating a pull request

**Comment by p-clem** [comment]
@musashiXXX 

Your branche resolved my problem !

**Comment by musashiXXX** [comment]
Great! I'd like to polish it a bit before I submit a pull request. I should be able to get it done sometime this week.



Sent from my Corvus® Corax™ Z, an RFC 1149 device. On the AT&T® Avian™ network.

-------- Original message --------
