### ISSUE TITLE
Custom manager assigned to objects property

### ISSUE THREAD

**Issue by DmitryFillo** [django-mptt/django-mptt#380]
class VisibleManager(TreeManager):
        def get_queryset(self):
            return super(VisibleManager, self).get_queryset().filter(is_hidden=False)

    class MyModel(MPTTModel):
        # ...
        objects_visible = VisibleManager()

Default django behaviour is not assign custom manager to ```MyModel.objects``` variable, but with django-mptt ```MyModel.objects``` and ```MyModel.objects_visible``` will be instance of ```VisibleManager```. I think that ```MyModel.objects``` must throws ```AttributeError``` as it in default django models. Why are these ([one](https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L331), [two](https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L335)) line needed?

**Comment by craigds** [comment]
That's a good point, it probably doesn't need to be there. I'm not sure why it is.

Is it causing problems though? I'm sure if I remove it, *someone* is going to be depending on it.

**Comment by DmitryFillo** [comment]
Not such a big problems, but this behaviour can deceive: you can expect standard behavior from ``objects``, but get custom behaviour from another manager. I think that is dangerous potentially.

I agree that is minor issue and someone can be depending on it.

**Comment by craigds** [comment]
Yes, you might expect that, but you'd generally be wrong to do so - django [doesn't set `objects`](https://docs.djangoproject.com/en/1.8/topics/db/managers/#manager-names) at all when you set another manager using a custom name, so in that case you should expect an `AttributeError` instead of expecting the 'default' `objects` behaviour.

I do agree that it's unnecessary. Perhaps it's worth removing for 0.8.

**Comment by craigds** [comment]
Coming back to this, I'm going to close it off. The extra manager doesn't seem to actually cause any problems; removing it would be a backwards-incompatible change with no real upside that I can see. Thanks for reporting it anyways :)
