### ISSUE TITLE
"TypeError: 'tuple' object does not support item assignment"  when save()

### ISSUE THREAD

**Issue by yjmade** [django-mptt/django-mptt#384]
https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L935

since args is a tuple and tuple is immutable, so set args element is unsupported.

**Comment by craigds** [comment]
That's a very specific edge case you've got there. Might I ask, what led to this?

Seems like you'd only get this if you called:

    model.save(False, False, None, None)

with *all* those arguments, and all positional (not as keywords args)

**Comment by yjmade** [comment]
I inherit MPTTModel and rewrite the save method like below to trigger the problem

```py
class Commodity(MPTTModel):
    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        ***dosomething***

        return super(Commodity, self).save(force_insert, force_update,
                                           using, update_fields)
```
