### ISSUE TITLE
Doctests do not run in Python 2

### ISSUE THREAD

**Issue by AndrewGrossman** [django-mptt/django-mptt#385]
I'm looking at master, with the change below in 5a4da0ffaf2015fef2ba272d92ca5d9e54aa427f to handle Unicode in PY3.

https://github.com/django-mptt/django-mptt/commit/5a4da0ffaf2015fef2ba272d92ca5d9e54aa427f#commitcomment-11988201

The doctest text never gets written into the temporary file buffer.

**Comment by craigds** [comment]
Aha! This explains a few mysterious 'I have no idea why this change breaks the tests on python 3 only' things over the last year or so ;)
