### ISSUE TITLE
django 1.9: cannot import name EMPTY_CHANGELIST_VALUE

### ISSUE THREAD

**Issue by colpaisa** [django-mptt/django-mptt#391]
Hello, "EMPTY_CHANGELIST_VALUE" is replace and remove in Django 1.9, please check this issue, probably create a pull for this in the coming days.

**"from django.contrib.admin.views.main import EMPTY_CHANGELIST_VALUE"**

**Comment by mrgaolei** [comment]
+1

**Comment by emorozov** [comment]
+1

**Comment by craigds** [comment]
I believe this is fixed since a9199d5a2a12cad69b8f350c2bf18925c9dfc102
