### ISSUE TITLE
MPTT model creation fails inside data migration file.

### ISSUE THREAD

**Issue by mani-zenefits** [django-mptt/django-mptt#392]
I have written a data migration file for creating some initial data for a MPTT model.

But the creation fails,

    def create_foo(apps, schema_editor):
        db_alias = schema_editor.connection.alias
        logger = logging.getLogger(__name__)

        Foo = apps.get_model("app", "Foo")

        for attr in ROLES:
            try:
               foo = Foo.objects.using(db_alias).get(name=attr[0])
           except Foo.DoesNotExist:
             parent = Foo.objects.using(db_alias).get(name=attr[1]) if attr[1] else None
             if parent:
                 foo = Foo.objects.create(name=attr[0], parent=parent)
             else:
                foo = Foo.objects.using(db_alias).create(name=attr[0])
                logger.info("Created foo - %s" % foo)

I am getting below error while executing below line.

    foo = Foo.objects.using(db_alias).create(name=attr[0])

File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler raise errorclass, errorvalue django.db.utils.IntegrityError: (1048, "Column 'lft' cannot be null")

**Comment by fritz-k** [comment]
The `TreeManager` which sets all mptt-attributes implicitly isn't available from within migrations. Without it, you have to manually set 'lft', 'rght', 'level' and 'tree_id' when creating objects. 

If you do not know these values in advance or don't care to manually set lots of these, you can set them all `0` and call `rebuild()` after the migrations. See my comment on https://github.com/django-mptt/django-mptt/issues/382#issuecomment-136151904 for an example.

**Comment by ArtemBernatskyy** [comment]
+1 for this issue

**Comment by maratumba** [comment]
Not an ideal workaround for this is to import the model from the actual app. For @mani-coder's example, this would be:
```
from app.models import Foo

def create_foo(apps, schema_editor):
    if hasattr(Foo,'_tree_manager'):
        Foo._tree_manager.rebuild()

class Migration(migrations.Migration):

    dependencies = [
        # ...
    ]

    operations = [
        migrations.RunPython(create_foo, migrations.RunPython.noop),
    ]
```
In order for this not to break, we make sure the model is still inheriting from `MPTTModel`. If in the future it gets removed, this should still work.
