### ISSUE TITLE
drilldown_tree_for_node order by count_attr

### ISSUE THREAD

**Issue by LennyLip** [django-mptt/django-mptt#394]
Hi, thanks for cool app!

I have a question, how to order by count_attr from drilldown_tree_for_node?

**Comment by LennyLip** [comment]
and second question

For example, i have

    mptt.utils.drilldown_tree_for_node(country, rel_cls=Item, rel_field="address_tree", count_attr="items_count", cumulative=True)

How to i can filter Item instances list count? 

Now it count all items for country children, but i want filter items to Items.objects.filter(category__pk=1) (for example).

**Comment by matthiask** [comment]
This is not possible currently. The code in `drilldown_tree_for_node` was written in 2008, before Django had any support for annotations and aggregations. 

A new version might use `get_family()` with some annotations for the count. Pull requests would be welcome. Thank you!
