### ISSUE TITLE
Reversed Ordering Regression

### ISSUE THREAD

**Issue by Gillingham** [django-mptt/django-mptt#399]
It seems like in some semi-recent django-mptt version release, the default insertion ordering was reversed.

Prior my tree was traversed in the same order I inserted, as I intended. Now there seems to be a regression where siblings are ordered by opposite of what they were. I tried downgrading to 0.6.x but couldn't easily get it working with my Django 1.8 code base.

**Comment by craigds** [comment]
This doesn't ring a bell, can you supply a test project or at least a code sample?

**Comment by matthiask** [comment]
Thanks for the report. 

I don't see why anything would have changed, please reopen if/when you have additional information. Thanks in advance!
