### ISSUE TITLE
django admin display errors on using django mptt

### ISSUE THREAD

**Issue by cyanqing** [django-mptt/django-mptt#409]
Hello, I'm using mptt 0.7.4 on django 1.9b1. When I running django project , the admin page displays as follows：

![untitled](https://cloud.githubusercontent.com/assets/11730943/10843395/c88816a4-7f33-11e5-8048-a9bae1e66b08.png)

It works with my Django 1.5 code base.

Thanks!

**Comment by craigds** [comment]
Struggling to reproduce this. What does the HTML for that bit look like? Does it work on django 1.8?
