### ISSUE TITLE
Move cache_tree_children to TreeManager

### ISSUE THREAD

**Issue by danielnaab** [django-mptt/django-mptt#413]
It would be great to be able to query a tree and get back an object that may be traversed using standard Python object notation. For example:

    # This (with the hypothetical use of `as_tree`) should result in only two database hits:
    root = TreeNode.objects.get(pk=1)
    tree_root = root.get_descendants(include_self=True).select_related('foreign_key').as_tree()
    for child in tree_root.children:
        print child.foreign_key.pk

If there a way to do this already I would be thrilled to know, as I need to deal with a tree among disparate pieces of code and it's not clear how to efficiently pass a node into a function that may traverse the tree without it triggering unnecessary DB hits.

I will create a separate package to do this if not a reasonable addition to the core library or there doesn't already exist a third-party page that does this. I'd appreciate some pointers on if that is the necessary path.

**Comment by danielnaab** [comment]
I see that `mptt.templatetags.mptt_tags.cache_tree_children` does what I'm looking for, but isn't documented. I will create a pull request documenting its use, but where should it go? Maybe just a FAQ entry?

Also, an observation: since the `cache_tree_filter` is useful outside the context of templates, perhaps the core implementation should not be in `mptt_tags`, but instead on the model manager?

**Comment by craigds** [comment]
Hi Daniel

Yes, moving it to the model manager would make sense (and log a deprecation warning for the templatetags one). Cheers

**Comment by danielnaab** [comment]
Hi Craig,

Thanks, I can look into doing that.

One additional question: It seems that `get_ancestors()`, along with `get_children()` should honor the cache. `get_children()` works perfectly, but although I see code that looks like `get_ancestors()` does, my tests show that accessing attributes on the nodes returned by it results in a db hit. Are there unit tests to confirm this functionality? I'm not certain if I'm doing something wrong or not.

Thanks!

**Comment by danielnaab** [comment]
FYI to anyone else who encounters this:

The issue I saw with extra DB hits was related to using methods on the related querysets, such as `get_ancestors().last()` or `get_children.all()`. Iterating over the results of `get_children()` or `get_ancestors()` directly doesn't result in db hits when using `cache_tree_children`.

**Comment by craigds** [comment]
FWIW there is a test that covers `get_ancestors()` using the cache (`RecurseTreeTestCase.test_cached_ancestors`)

**Comment by craigds** [comment]
Thanks :)

One issue with putting this on the queryset is that it can no longer support lists of nodes, but only querysets. I'm pretty sure there are people using this (I have in the past).

Perhaps it could go on the manager, and be called by the queryset? Alternatively, leave it in a utility function and call it from the queryset version (and the deprecated templatetag version).

one other thing - the deprecation note about passing nodes in the wrong order should probably be removed, since 0.8 is near. It should throw a ValueError in that case instead.

Sound reasonable?

**Comment by danielnaab** [comment]
@craigds, sure I'll take a look tonight

**Comment by danielnaab** [comment]
@craigds, I updated by moving the function into `utils` and calling it from the templatetag. I removed the `DeprecationError` you mentioned, and also the one I added to the original `cache_tree_children` tag, which can just act as an alias to the util function.

**Comment by craigds** [comment]
fixed via #416 , thanks :)
