### ISSUE TITLE
Release a version compatible with Django 1.9

### ISSUE THREAD

**Issue by patrys** [django-mptt/django-mptt#415]
The current master seems to work fine on 1.9 but the last released version does not. Seeing that Django 1.9 has been officially released, it would be nice to have a compatible release of `django-mptt`.

**Comment by Wtower** [comment]
Relevant issue #402

**Comment by simion** [comment]
I get "apps aren't loaded yet" error when i import MPTTModel in my project's models. Therefore, i cannot upgrade my project to django 1.9
Am I doing something wrong, or django-mptt needs updates for 1.9 compatibility?

**Comment by craigds** [comment]
@simion are you using django-mptt master, or a released version? Was your project working okay with django 1.8?

**Comment by simion** [comment]
Released version, from pypi.
project works fine on 1.8, implementation is made correctly

**Comment by craigds** [comment]
Master is now tested on django 1.9. Since I've dropped support for django 1.4,1.6,1.7 and python 2.6 since 0.7 was released, this will need a 0.8 release (not just a 0.7.5).

There is one issue in the 0.8 milestone still, if someone could address that it'd be great, or I can get to it hopefully a week or so away

**Comment by andrewdodd** [comment]
+1

**Comment by thecardcheat** [comment]
Looks like that 0.8 milestone is complete, so will there be a release soon?

**Comment by frennkie** [comment]
+1

**Comment by Wtower** [comment]
I think #420 is very important to tackle before releasing 0.8.

Also there might be another issue with some maximum recursion depth, I want to be sure before posting a new issue (yet) but it looks pretty nasty.

**Comment by craigds** [comment]
Can a few people confirm that they've tested the latest master and it's working okay?

**Comment by claudep** [comment]
What about releasing a rc? This would ease testing a bit with `pip install --dev django-mptt`.

**Comment by Wtower** [comment]
Relevant issue #424

**Comment by matthiask** [comment]
Thank you @craigds. FWIW everything seems to work fine here.

**Comment by sspross** [comment]
@craigds it seems to work here as well, django 1.9 and feincms 1.11.3! thx a lot!

**Comment by claudep** [comment]
master seems to run fine for my use cases, thanks!

**Comment by craigds** [comment]
All relevant tickets have been dealt with now, so I've just released 0.8.0 :)

pypi: https://pypi.python.org/pypi/django-mptt/0.8.0

Thanks for your help with testing and tracking down the last few issues.

**Comment by matthiask** [comment]
Great, thanks!
