### ISSUE TITLE
`tree_item_iterator` relationships mixed when filtering item list.

### ISSUE THREAD

**Issue by joshuajonah** [django-mptt/django-mptt#418]
I'm having a strange one here.

If I supply a filter to a queryset of mptt objects, then supply that qs to `tree_item_iterator`, the relationships are all messed up.

#### Example

In the Django admin my tree appears correct:

![django-admin-tree](http://i.imgur.com/MeSk68m.png)

However if I do this:

    category_qs = Category.objects.filter(pk__in=list_of_pks)
    for c in tree_item_iterator(category_qs, ancestors=True):
        print c

I get this output:

	(<Category: BREAD>, {u'new_level': True, u'ancestors': [], u'closed_levels': []})
	(<Category: VACUUM>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: POLY>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: GARBAGE>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: PRODUCE>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: SELF CLOSURE>, {u'new_level': False, u'ancestors': [], u'closed_levels': [1]})
	(<Category: TABLE COVER>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: SAW BLADES>, {u'new_level': True, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: BOOKS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: GRINDER & EQUIPMENT>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: CASINGS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: FREEZER PAPER>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: MISCELLANEOUS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: STUFFING/COATER/MARINADE>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: BINDER>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: SEASONING & SPICES>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: GRAVY>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: OTHER INGREDIENTS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: EQUIPMENT>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: CLEANERS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: PAPER TOWELS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: TOILET PAPER>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: BUBBLE 3/16">, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: BUBBLE 1/2">, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: PEANUTS>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: TAPE>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: PALLET WRAP>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: CORRUGATED>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: STRAPPING>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: CAKE>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: SAUSAGE>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: INSERT>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: PATTY>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: INDUSTRIAL>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': []})
	(<Category: PIZZA>, {u'new_level': False, u'ancestors': [u'TABLE COVER'], u'closed_levels': [1]})
	(<Category: TAKE AWAY SUPPLIES>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: PLATES/TRAYS/CONTAINERS>, {u'new_level': True, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: CUTLERY>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: CONDIMENTS>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: NAPKINS>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: PLASTIC>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: SILVER>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: GOLD>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: COFFEE & FILTERS>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: ENVELOPE>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': []})
	(<Category: TAGS>, {u'new_level': False, u'ancestors': [u'TAKE AWAY SUPPLIES'], u'closed_levels': [1]})
	(<Category: DISPENSER>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: ELASTICS>, {u'new_level': False, u'ancestors': [], u'closed_levels': []})
	(<Category: PIPING BAGS>, {u'new_level': True, u'ancestors': [u'ELASTICS'], u'closed_levels': []})
	(<Category: BAKING CUPS>, {u'new_level': False, u'ancestors': [u'ELASTICS'], u'closed_levels': [1]})

The ancestors are completely wrong. Is this a bug? or am I doing something I shouldn't be?

**Comment by mlorant** [comment]
Got the same problem using `tree_item_iterator`. I see the ticket has been closed, so I suppose @joshuajonah find out a solution. Could you share it with us? :)

**Comment by mlorant** [comment]
Ok, found it after one hour of search... Do not put an `ordering` settings in the `Meta`  of your model. Elements was sorted by a field non related to mptt and the algorithm used by the method did not worked in this case.
