### ISSUE TITLE
type object 'Category' has no attribute 'tree'

### ISSUE THREAD

**Issue by Six-wars** [django-mptt/django-mptt#421]
I'm trying to migrate a site with django-mptt 0.5.4 on the destination server I get the error

Environment:

Request Method: GET
Request URL: http://stage.kenyabuzz.com/accounts/signup/

Django Version: 1.7.10
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.redirects',
 'django.contrib.humanize',
 'autocomplete_light',
 'djangorestframework',
 'haystack',
 'lamusoftware.generic',
 'mptt',
 'bootstrapform',
 'sorl.thumbnail',
 'oauth2client',
 'articles',
 'banners',
 'common',
 'directory',
 'events',
 'galleries',
 'marketplace',
 'movies',
 'pages',
 'profiles',
 'search',
 'stats',
 'minidetector',
 'mobile',
 'reports',
 'favorites',
 'braces',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'allauth.socialaccount.providers.facebook',
 'widget_tweaks',
 'wordofmouth',
 'ckeditor',
 'django_mobile',
 'markup_deprecated',
 'whoosh',
 'rest')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
 'minidetector.Middleware',
 'mobileesp.middleware.MobileDetectionMiddleware',
 'kb.middleware.log_ip_middleware.SetRemoteAddrFromForwardedFor',
 'kb.middleware.log_ip_middleware.RedirectMovie')

Traceback:
File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/kbuzz/lib/python2.7/allauth/account/views.py" in dispatch
  62.                                             **kwargs)
File "/home/kbuzz/lib/python2.7/allauth/account/views.py" in dispatch
  133.                                                           **kwargs)
File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/views/generic/edit.py" in get
  162.         form = self.get_form(form_class)
File "/home/kbuzz/webapps/kenyabuzz/lib/python2.7/Django-1.7.10-py2.7.egg/django/views/generic/edit.py" in get_form
  45.         return form_class(**self.get_form_kwargs())
File "/home/kbuzz/lib/python2.7/allauth/account/forms.py" in __init__
  240.         super(SignupForm, self).__init__(*args, **kwargs)
File "/home/kbuzz/lib/python2.7/allauth/account/forms.py" in __init__
  187.         super(BaseSignupForm, self).__init__(*args, **kwargs)
File "/home/kbuzz/webapps/kenyabuzz/kb/profiles/forms.py" in __init__
  62.         events_cart = Category.tree.filter(level=1, tree_id__in=[x.tree_id for x in me])

Exception Type: AttributeError at /accounts/signup/
Exception Value: type object 'Category' has no attribute 'tree'

**Comment by craigds** [comment]
0.5.4's pretty old now. but you probably just need to change `.tree` to `.objects`

See http://django-mptt.github.io/django-mptt/upgrade.html#treemanager-is-now-the-default-manager-yourmodel-tree-removed

**Comment by Six-wars** [comment]
Thanks I "think" I did or found a fix for it, it's working now.
