### ISSUE TITLE
Exception Value: 	  get_cached_trees() called on a queryset with the wrong ordering: ['lft']

### ISSUE THREAD

**Issue by Reivax84** [django-mptt/django-mptt#422]
after updating i have problems with the following lines, disabling the test an all is ok. i cant find anything that i would have to change in my model to make it work again :/

mptt/utils.py  line 221

  # If ``queryset`` is QuerySet-like, set ordering to depth-first
    if hasattr(queryset, 'order_by'):
        mptt_opts = queryset.model._mptt_meta
        tree_id_attr = mptt_opts.tree_id_attr
        left_attr = mptt_opts.left_attr
        if tuple(queryset.query.order_by) != (tree_id_attr, left_attr):
            raise ValueError(
                "get_cached_trees() called on a queryset with the wrong " +
                "ordering: %r" % (queryset.query.order_by,))

**Comment by craigds** [comment]
What does your model/queryset look like? How are you calling this code?

**Comment by Reivax84** [comment]
model: 
class Infrastructure(MPTTModel):
    name = models.CharField(max_length=255)
    client = models.ForeignKey(Client)
    notes = models.TextField(blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    class Meta:
        #ordering = ('client', 'name') 'tree_id', 'lft'
        unique_together = ['name', 'parent']
        permissions = (('view_infrastructure', 'Can view Infrastructure'),)

    class MPTTMeta:
        order_insertion_by = ['tree_id', 'lft', 'name']

    def __str__(self):
        return "%s" % (self.name)

    def get_absolute_url(self):
        return reverse("infrastructure:infrastructure_list", kwargs={'pk': self.pk})

I'am calling the code in a template:
{% recursetree infrastructure.get_ancestors %}
            <li>
                <a href="{% url 'infrastructure:infrastructure_list' node.pk %}">{{ node.name }}</a>
            </li>
            {{ children }}
 {% endrecursetree %}

**Comment by craigds** [comment]
Aha. Turns out get_ancestors() does `.order_by('lft')`, because ancestors are necessarily in the same tree, so `.order_by('tree_id', 'lft')` seemed unnecessary.

This queryset is correct, so I think perhaps `cache_tree_children` is just being overly annoying here. If the queryset wasn't correct a ValueError would get raised further down anyway.

**Comment by Reivax84** [comment]
thx great support :)
