### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Wtower** [django-mptt/django-mptt#424]
With Django 1.9 and django-mptt master: https://github.com/django-mptt/django-mptt/commit/0199fa61bc4561952905f8f4279281cee6c52d74 (as of today Dec 14), I get the error:

    RuntimeError: maximum recursion depth exceeded

The function responsible for this is `get_ancestors()`. Has something changed in how we should use this?

This does not happen with Django 1.8.7 and django-mptt 0.7.4.

The exact piece of code that breaks it is https://github.com/Wtower/django-ninecms/blob/7b13262120dd560a58cb1604931b9b9ec8c403f0/ninecms/templatetags/ninecms_extras.py#L136

The stack trace is enormous so I present only the (apparently) relevant part and attach the full.

    December 14, 2015 - 11:07:11
    Django version 1.9, using settings 'ttours.settings'
    Starting development server at http://127.0.0.1:8000/
    Quit the server with CONTROL-C.
    Internal Server Error: /el/about/
    Traceback (most recent call last):
      File "/home/gkarak/.virtualenvs/ttours/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
    ...
      File "/home/gkarak/.virtualenvs/ttours/lib/python3.4/site-packages/django/db/models/sql/query.py", line 2011, in add_to_dict
        data[key] = {value}
    RuntimeError: maximum recursion depth exceeded

[django-mptt-maximum-recursion.txt](https://github.com/django-mptt/django-mptt/files/61034/django-mptt-maximum-recursion.txt)

**Comment by craigds** [comment]
Could you post your model code? It _looks_ like maybe you're attempting to use a ManyToManyField (or a reverse ForeignKey) in your `order_insertion_by`?

**Comment by Wtower** [comment]
My pleasure, I'd like to help with this as much I can.

The model code is here: https://github.com/Wtower/django-ninecms/blob/7b13262120dd560a58cb1604931b9b9ec8c403f0/ninecms/models.py#L178

The `order_insertion_by` field is a plain `IntegerField`. What strikes me is that this works ok with 0.7.4.

**Comment by craigds** [comment]
The telling part of this stack trace is that this is in `DeferredAttribute.__get__`. Is this in a `.defer()` or `.only()` call? If so this might be the same issue as #176. I don't know why this would start happening after 0.7.4 though.

Could you provide an easy way to reproduce the issue (e.g. a smallish test project which reproduces the problem)? I was previously unable to reproduce #176.

**Comment by Wtower** [comment]
I have created a small (as possible) example in https://github.com/Wtower/django-mptt-424

There is no `.defer()` or `.only()` involved directly, only `.get_descendants()` as I describe in README. I hope this will help approach both issues better. Please feel free to ask me for any changes if you like!

**Comment by craigds** [comment]
Thanks, that's really helpful, reproduces the problem.

It looks like this is similar to #176 but caused by django-mptt itself (it uses an `.only()` call in `get_descendants()`, which previously didn't trigger the problem but seems to recently.

**Comment by Wtower** [comment]
Very glad to have helped, indeed the issue has gone. Many thanks.
