### ISSUE TITLE
'NoneType' object has no attribute 'tree_id'

### ISSUE THREAD

**Issue by robslotboom** [django-mptt/django-mptt#428]
Updating a root elements fiels which is the "order_insertion_by" raises:

'NoneType' object has no attribute 'tree_id'

I solved this bij adding two lines of code.

    def _make_sibling_of_root_node(self, node, target, position):
        ...
        elif position == 'right':
            if target_tree_id > tree_id:
                new_tree_id = target_tree_id
                lower_bound, upper_bound = tree_id, target_tree_id
                shift = -1
            else:
                right_sibling = target.get_next_sibling()
                if node == right_sibling:
                    return
                # Addition
                if not right_sibling:
                    return
                # end of addition
                new_tree_id = getattr(right_sibling, self.tree_id_attr)
                lower_bound, upper_bound = new_tree_id, tree_id
                shift = 1

**Comment by matthiask** [comment]
Thank you for the report! Do you have some additional details such as the model itself? Will probably be a big help for constructing a test case.

**Comment by mullakhmetov** [comment]
I got the same error.
Environment: python 2.7.10, Django 1.9.1, django-mptt 0.8.4
```
# models.py
class Foo(MPTTModel):
    test = models.CharField(max_length=5)
    parent = TreeForeignKey('self', null=True, blank=True)
```
![screen shot 2016-07-20 at 17 06 39](https://cloud.githubusercontent.com/assets/5443029/16989577/6ffb8ac2-4e9d-11e6-9b1f-749177230c84.png)

**Comment by matthiask** [comment]
Nice, now I can reproduce this, even without `order_insertion_by`.

It seems that setting `parent_id` does not reset `parent` in any way, resp. `parent` isn't dynamically loaded from the database just because the underlying id field has some value.

(As you have seen assigning `parent` directly works fine.)

**Comment by matthiask** [comment]
Additional testing reveals that this works:

```
f1 = Foo.objects.create()
f2 = Foo.objects.create()
f2.parent_id = f1.id
del f2._parent_cache  # Remove cached value of "None"
f2.save()
```
