### ISSUE TITLE
get_family() not returning entire family of root node in mptt

### ISSUE THREAD

**Issue by veris-neerajdhiman** [django-mptt/django-mptt#432]
I am using django mptt for tree structure. I ma adding parent to any object while updating not creating any object as shown below .

```user= User.objects.create(username='abc')``` 

after some logics or steps when we are sure that it can be added as a child of some user the I am updating the user instance.

``User.objects.filter(pk=user.pk).update(parent=parent_user_instance)``

user is added as the parent and when I'll do ```user.get_siblings()``` I'll get all siblings but when I'll do ```user.get_family()``` then it fails to fetch its ancestors or descendant .

two important things here are :

1 ) Built in User model (django auth_user) of django is extended to enable mptt .

2 ) I am adding parent through ```update()``` not create() # I am not sure ```update()``` have something to do with the issue.

**Comment by matthiask** [comment]
Thanks for the report. Using `QuerySet.update` is quite definitely the reason for the problem you're seeing here, because that one does not update mptt's bookkeeping attributes (tree_id, lft, rght, level).

Try again with `user.refresh_from_db(); user.parent = parent_user_instance; user.save()`

**Comment by veris-neerajdhiman** [comment]
will the same logic work for self parent. I have tried for self parent and it is giving the following error 

`mptt.exceptions.InvalidMove: A node may not be made a child of itself.`

Other alternative of my original problem is to use ``move_to`` instead of update. But the same self parent issue comes with ``move_to`` too which is obvious because it can't move himself.. 

So I have used the following approach for now

```
try:
     user.move_to(User.objects.get(pk=user.pk), position='last-child')           
except:
       User.objects.filter(pk=user.pk).update(parent=User.objects.get(pk=parent_user.pk))
```
So whenever `move_to` will raise ant error (usually it will failed for self parent) the `update()` will be us

**Comment by matthiask** [comment]
The `except:` branch **will** destroy your tree, and **will** lead to problems down the road if you don't rebuild (`User.objects.rebuild()`). 

You must not ignore the `InvalidMove` exception — the error message you're getting means that you're trying to build a graph with cycles instead of a tree, and mptt does not support graphs, only trees.

**Comment by veris-neerajdhiman** [comment]
But I think self parent is allowed in mptt  ?
also rebulid() will affect performance if there are large number of users in Db.

**Comment by matthiask** [comment]
A node being its own parent is a cycle, and cycles are not allowed in trees. Therefore this is not allowed in mptt.

**Comment by matthiask** [comment]
Closing for now, because this seems to be a usage error, not an error in the django-mptt library.

**Comment by veris-neerajdhiman** [comment]
@matthiask Thanks for the help. Appreciate your swift and honest response. :)

**Comment by matthiask** [comment]
You're welcome, @veris-neerajdhiman :-)
