### ISSUE TITLE
Issues with existing data when change non-mptt model to mptt

### ISSUE THREAD

**Issue by verisadmin** [django-mptt/django-mptt#433]
I have changed default Django `User` model to `mptt`. But for exiting users mptt is behaving un- expectedly . I think when we run migrations and we need to choose default values for `level, left, right` . Then whatever value we choose it will create issues at some point.

`E.g.,` I'll explain what I did and what I got then you will get an idea about the issue.

- I changed `User` model to mptt by adding parent field. 
- run makemigreations an then it asks for default values of not null fields , `leve, lft , rgt, tree_id` etc.
- I have chooses `0` as default value.
- after successful migrations I opened the python shell and import mptt `User` model
- `u1 = User.objects.get(username='admin')` 
- Now when I'll do `u1.get_family()` , It returns me entire users as its family (which is right I think because I have defined default values as 0 ) which is wrong.
- Also `get_family()` is returning all users irrespective of the user instance I am using e.g., 
`u2 = User.objects.get(username="abc")`
`u2.get_family()` returns all users again.

I hope you understand the issue with my above example, so there is any fix for this or should I defined `level, lft , rgt` field to in models an make them `null= true` , if yes then what will be the type of these fields.

**Comment by verisadmin** [comment]
I am not sure but can rebuliding the tree will solve my problem ?  `User._tree_manager.rebuild()`

**Comment by craigds** [comment]
Yes, the only way to do this at present is just to set everything to 0 and then call rebuild after the migration. #195 notes that. #382 is also relevant

**Comment by Usamaraoo** [comment]
![Screenshot - 7_21_2020 , 8_49_38 PM](https://user-images.githubusercontent.com/42535017/88076652-c4c38380-cb93-11ea-964a-140e047928da.png)
i have csv file witch i have imported on mysql it has data related counrty , state, city how can i apply mptt on it parent and level already given in the file
