### ISSUE TITLE
DraggableMPTTAdmin improvements / setup.py troubles

### ISSUE THREAD

**Issue by matthiask** [django-mptt/django-mptt#434]
Collecting a few problems with the current implementation of DraggableMPTTAdmin here (I'm working on those right now)

- [x] Make the implementation CSP-compatible (no inline JavaScript)
- [x] Remove the customized base template — use stock `admin/change_list.html` instead
- [x] When using filters, the `div#module.changelist` should also have the `filtered` class, otherwise filters overlap the change list area and hide cells beneath it

**Comment by darkowic** [comment]
@matthiask what will happened with this? Will you continue it?

**Comment by matthiask** [comment]
@darkowic Even better — the changes mentioned above have already hit master. I just forgot to mark the individual items as done!

**Comment by darkowic** [comment]
Nice! I used old library with move functionality from feincms https://bitbucket.org/san/django-mptt-tree-editor and now I want to upgrade django but this is very nice feature :) Do you know when will it be released?

**Comment by matthiask** [comment]
I don't know, but maybe @craigds can shed some light on this matter? We don't have any backwards-incompatible changes since 0.8, so maybe a release could be made quickly?

**Comment by craigds** [comment]
I don't have any particular plans for 0.9, and no objection to releasing this in principle.

Though 0.8 is only 3 months old, and I've been sticking to supporting the last two minor releases. So releasing 0.9 would mean stopping supporting 0.7, which I'm not really happy with doing yet.

I suppose I could release master as 0.8.1 given that there's no backward-incompatible changes. This draggable admin is a substantial win, so it'd be a shame to wait ages for users to get it.

**Comment by matthiask** [comment]
Great idea! Didn't think of that.

**Comment by craigds** [comment]
Done :)

**Comment by matthiask** [comment]
Awesome! Thank you :)

On Fri, Feb 26, 2016 at 11:27 PM, Craig de Stigter <notifications@github.com
> wrote:

> Done :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/django-mptt/django-mptt/issues/434#issuecomment-189508661>
> .
>



-- 
Matthias Kestenholz
Partner, Programmierung

FEINHEIT AG
Molkenstrasse 21
8004 Zürich
www.feinheit.ch

**Comment by darkowic** [comment]
Thank you guys! You are awesome!

**Comment by mpachas** [comment]
@craigds Hi! I've just tried pypi install of 0.8.1 but it comes with no static folder, so I have both 404:
```
"GET /static/mptt/draggable-admin.css HTTP/1.1" 404 1685
"GET /static/mptt/draggable-admin.js HTTP/1.1" 404 1682
```
Thanks!

**Comment by matthiask** [comment]
Oh no. My bad! Fixed in f823958e35f54974710d5a92ce7326d2cd5a474e, sorry @craigds .

**Comment by craigds** [comment]
Thanks guys. I've just released that as 0.8.2 :)

**Comment by matthiask** [comment]
Oh no (2). MPTT's `setup.py` still uses `package_data={...}`. I'll have a real fix ready today. Really sorry, I obviously didn't test this well enough :-(

(WIP: https://github.com/matthiask/django-mptt/commit/76d1d338c87b57c65343e81416fb54f35fd943b0)

**Comment by matthiask** [comment]
@craigds Feeling bad now. But I've finally fixed it.

Minimal commit for `master` (verified twice in pristine virtualenvs): https://github.com/django-mptt/django-mptt/commit/c3d7d94fcf60185af995b88c81b480d5c2134394

Pull request which simplifies `setup.py` so that stuff like this does not happen again: https://github.com/django-mptt/django-mptt/pull/439

**Comment by craigds** [comment]
@matthiask no problem. making omelette requires breaking eggs. Thanks for the fix
