### ISSUE TITLE
Question / feature request: Bulk create tree from root node

### ISSUE THREAD

**Issue by jmcarp** [django-mptt/django-mptt#442]
As far as I can tell from the docs and the source, inserting nodes with tree properties (`lft`, `rght`, etc.) requires multiple database queries, even when passing flags like `save=False`. If a user wants to bulk-insert a large number of nodes on a tree that doesn't yet exist, it seems like they have to disable mptt, insert the nodes, and then rebuild the relevant partial tree. Instead, it should be possible to set all tree properties in python and do a single bulk insert. This would only work when the user wants to bulk create nodes in a tree that doesn't exist yet, so that it's safe to skip calling `_create_space` and other helpers that move around existing nodes. I'm imagining an interface like this:

``` python
nodes = [Node(**obj) for obj in objs]
set_tree_properties(nodes)
Node.manager.bulk_create(nodes)
```

Where `set_tree_properties` sets `tree_id`, `lft`, and `rght` on all nodes without touching the database. The idea is to create an entire tree with a single request, without the need for a potentially expensive `rebuild`.

Does this make sense? Would there be interest in adding a feature like this? I wrote a very simple implementation of `set_tree_properties` for a project I'm working on that I'd be happy to contribute, if it would be worthwhile.

**Comment by craigds** [comment]
Sounds awesome. When would you move the other existing nodes to make space in the tree? During `bulk_create` ?

**Comment by jmcarp** [comment]
So in the specific use case I'm working with, there aren't any existing nodes in the tree, which is why it's safe to set `lft` and `rght` without talking to the database other than calling `bulk_create`. If there are already existing nodes in the tree, it should still be possible to insert a new subtree in two queries: one to `bulk_create` all the new nodes, and a second to increment the `lft` and `rght` values of all nodes to the right of the inserted subtree.

To be more concrete, here's the helper I'm using myself:

```python
def treeify(node, pos=1):
	node['lft'] = pos
	for child in node.get('children', []):
		pos = treeify(child, pos=pos + 1)
	pos = pos + 1
	node['rght'] = pos
	return pos
```

Given a dict to be transformed into a tree of nodes, we can just call `treeify(root)`. If we're inserting a new subtree into an existing tree, we can pass the starting position, then increment the positions of the existing nodes as needed: `treeify(root, pos=start_pos)`, then an `UPDATE` for the rest of the nodes.

The first use case (new tree) is really simple, and I think the second use case (new subtree) would also be straightforward. Curious to hear what you think!

**Comment by erez-o** [comment]
+1 looks great.

@craigds , can you please confirm that when creating a new tree there aren't any loopholes in this method?
