### ISSUE TITLE
Unable to query MPTTModel "flatly"

### ISSUE THREAD

**Issue by wengole** [django-mptt/django-mptt#447]
I'm trying to build a query to find duplicates within a given tree. My Django query looks like this:

```python
readingorder = ReadingOrder.objects.get(pk=64)
readingorder.readingorderbook_set.values('book__id').annotate(book_count=Count('book__id')).query
```

The raw SQL should be something like

```sql
SELECT "books_readingorderbook"."book_id", COUNT("books_readingorderbook"."book_id") AS "book_count" 
FROM "books_readingorderbook" 
WHERE "books_readingorderbook"."reading_order_id" = 64 
GROUP BY "books_readingorderbook"."book_id"
```

That SQL would give counts of each book_id, I can then filter where this is greater than 1 to remove duplicates.

However as TreeManager is the default manager and this orders all QuerySets by tree position, the SQL is modified to:

```sql
SELECT "books_readingorderbook"."book_id", COUNT("books_readingorderbook"."book_id") AS "book_count" 
FROM "books_readingorderbook" 
WHERE "books_readingorderbook"."reading_order_id" = 64 
GROUP BY "books_readingorderbook"."book_id", "books_readingorderbook"."tree_id", "books_readingorderbook"."lft" 
ORDER BY "books_readingorderbook"."tree_id" ASC, "books_readingorderbook"."lft" ASC
```

which results in each book_id only having a count of 1.

It would be great if there was a TreeManager method that allowed you to ignore the tree order when making queries. Also I'm not sure what the reason was for removing the .tree manager and overriding the default, but having the Django default Manager here would have also solved my issue.

For reference, my models are this:

```python
class ReadingOrder(models.Model):
    name = models.TextField()
    source = models.URLField(
        max_length=1024,
        blank=True)
    books = models.ManyToManyField(
        to='Book',
        related_name='reading_orders',
        through='ReadingOrderBook')

    def __str__(self):
        return self.name


class ReadingOrderBook(MPTTModel):
    reading_order = models.ForeignKey(
        to='ReadingOrder')
    book = models.ForeignKey(
        to='Book')
    previous = TreeForeignKey(
        to='self',
        on_delete=models.SET_NULL,
        related_name='next',
        null=True,
        blank=True)

    class Meta(object):
        unique_together = (
            'reading_order',
            'book')

    class MPTTMeta(object):
        parent_attr = 'previous'

    def __str__(self):
        return '{} ({})'.format(self.book, self.reading_order)
```

**Comment by matthiask** [comment]
Does adding an empty `.order_by()` help? 

(Also see https://docs.djangoproject.com/en/1.9/topics/db/aggregation/#interaction-with-default-ordering-or-order-by )

**Comment by matthiask** [comment]
@wengole Any success? It seems to me that the particular behavior you're seeing has nothing to do with mptt, and everything with how Django handles default ordering.

That may be wrong though.

**Comment by wengole** [comment]
@matthiask Sorry for the delay in replying. I was actually trying to use this in migrations, but was testing fist in a shell. However in migrations, MPTT manager doesn't get loaded so it worked how I wanted.

I've just now tested what you suggested and that works fine.

```python
readingorder.readingorderbook_set.order_by().values('book__id').annotate(book_count=Count('book__id'))
```
results in SQL
```sql
SELECT "books_readingorderbook"."book_id", COUNT("books_readingorderbook"."book_id") AS "book_count" FROM "books_readingorderbook" WHERE "books_readingorderbook"."reading_order_id" = 64 GROUP BY "books_readingorderbook"."book_id"
```

**Comment by matthiask** [comment]
Thanks! 

Since this is Django's documented behavior I'm closing this issue.
