### ISSUE TITLE
Source releases of django-mptt 0.8.3 contain pyc files

### ISSUE THREAD

**Issue by suutari-ai** [django-mptt/django-mptt#450]
It seems that the source release (*.tar.gz and *.whl) of django-mptt 0.8.3 as distributed in PyPI are broken, since it they have pyc files. This causes some problems when installing django-mptt 0.8.3, since the pyc files could be for different python version.

The problem shows up as following error when running "setup.py install":

```
Running django-mptt-0.8.3/setup.py -q bdist_egg...
...
ValueError: bad marshal data (unknown type code)
```

A more detailed error can be seen on Shoop's documentation build log at readthedocs: http://readthedocs.org/projects/shoop/builds/3780065/

**Comment by suutari-ai** [comment]
The cause is probably these files in MANIFEST.in:
```
recursive-include tests *
recursive-include mptt/templates *
recursive-include mptt/locale *
recursive-include mptt/static *
```

Since they cause also pyc files to be included. I'll create a PR to fix this...

**Comment by craigds** [comment]
Thanks. Fixed by #451

**Comment by suutari-ai** [comment]
Thanks for including my fix!  Do you have plans for 0.8.4 release? Would be nice to get this fix to PyPI soon. :-)

**Comment by craigds** [comment]
0.8.4 is now in PyPI including this fix :)

**Comment by suutari-ai** [comment]
Great! Thanks!
