### ISSUE TITLE
get_descendants not returning all descendants

### ISSUE THREAD

**Issue by jmerkow** [django-mptt/django-mptt#452]
I have a MPTT model that is not returning all descendants when get_descendants is called

```
class LabelTree(MPTTModel):
    name = models.CharField(max_length=64,db_index=True)
    description = models.TextField(blank=True)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    class MPTTMeta:
        order_insertion_by = ['name']

    def __str__(self):
        return "[{}] {}".format(self.get_root().name,self.name)
```
 
`print('\n'.join([str(a) for a in root.get_children()]))`:

> [root1] OK
> [root1] NOTOK

`print('\n'.join([str(a) for a in root.get_descendants()]))`:

> [root1] root1
> [root1] OK
> [root1] OUTSIDE
> [root1] AX1
> [root1] AX2
> [root1] NOT
> [root1] MUSIC
> [root1] ART
> [root1] METAL
> [root1] MOTION
> [root1] ORB
> [root1] PAINT
> [root1] SCULPT

The nodes in subtree 'NOTOK' are missing, including NOTOK itself.
`get_family` give the same result, `get_leafnodes` only returns nodes from the OK subtree.

The template (copied from http://django-mptt.github.io/django-mptt/tutorial.html) shows all nodes and children appropriately.

**Comment by django-mptt** [comment]
Can you post the results of
`mptt.utils.print_debug_info(LabelTree.objects.all())` ?

**Comment by jmerkow** [comment]
The names are slightly different.

> pk,level,parent_id,tree_id,lft,rght,pretty
> 192,0,,1,1,80,[root1] root1
> 219,1,192,1,2,27,- [root1] OK
> 228,2,219,1,3,8,- - [root1] NL
> 230,3,228,1,4,5,- - - [root1] AX1
> 229,3,228,1,6,7,- - - [root1] AX2
> 220,2,219,1,9,24,- - [root1] NOTE
> 221,3,220,1,10,11,- - - [root1] Q
> 223,3,220,1,12,13,- - - [root1] ART
> 222,3,220,1,14,15,- - - [root1] METAL
> 224,3,220,1,16,17,- - - [root1] MUSIC
> 227,3,220,1,18,19,- - - [root1] ORB
> 225,3,220,1,20,21,- - - [root1] SCULPT
> 226,3,220,1,22,23,- - - [root1] PAINT
> 231,2,219,1,25,26,- - [root1] OKUNK
> 193,1,192,1,28,79,- [root1] NOTOK
> 201,2,193,1,29,30,- - [root1] Z
> 211,2,193,1,31,46,- - [root1] A
> 215,3,211,1,32,39,- - - [root1] B
> 218,4,215,1,33,34,- - - - [root1] C
> 216,4,215,1,35,36,- - - - [root1] D
> 217,4,215,1,37,38,- - - - [root1] E
> 212,3,211,1,40,45,- - - [root1] F
> 214,4,212,1,41,42,- - - - [root1] G
> 213,4,212,1,43,44,- - - - [root1] H
> 200,2,193,1,47,48,- - [root1] I
> 207,2,193,1,49,56,- - [root1] J
> 209,3,207,1,50,51,- - - [root1] K
> 210,3,207,1,52,53,- - - [root1] L
> 208,3,207,1,54,55,- - - [root1] M
> 202,2,193,1,57,66,- - [root1] N
> 204,3,202,1,58,59,- - - [root1] O
> 205,3,202,1,60,61,- - - [root1] P
> 206,3,202,1,62,63,- - - [root1] Q
> 203,3,202,1,64,65,- - - [root1] R
> 197,2,193,1,67,72,- - [root1] S
> 198,3,197,1,68,69,- - - [root1] T
> 199,3,197,1,70,71,- - - [root1] U
> 194,2,193,1,73,78,- - [root1] V
> 196,3,194,1,74,75,- - - [root1] W
> 195,3,194,1,76,77,- - - [root1] Y

**Comment by daleobrien** [comment]
I had this issue too when I was creating a lot or relationships on a list of objects. It turned out that each object needed to have refresh_from_db() called before making new relationship between a object and it's new parent. After I made that change everything came good.

**Comment by ad-m** [comment]
@daleobrien , do you can provide tests code which fail?

**Comment by daleobrien** [comment]
@ad-m Not really because I didn't end up finding a bug. Here's the sort of code that was in my tests,
models:
```python

from mptt.models import MPTTModel, TreeForeignKey

class Node(MPTTModel):
    parent = TreeForeignKey('self', null=True, blank=True,
                            related_name='children', db_index=True)

```
And my test
```python
from django.test import TestCase

class NodeTest(TestCase):

    def setUp(self):
        '''
               0
              / \
             /   \
            1     2
           / \   / \
          3   4 5   6
        '''

        nodes = [Node() for _ in range(7)]

        for parent, children in [(0, [1, 2]),
                                 (1, [3, 4]),
                                 (2, [5, 6])]:
            for child in children:
                nodes[parent].refresh_from_db()  # <- Need this, else errors
                nodes[child].parent = nodes[parent]
                nodes[child].save()

        self.nodes = nodes

    def _get_descendants_for(self, idx, include_self):
        return set(self.nodes[idx].get_descendants(include_self=include_self))

    def test_get_descendants_full_tree(self):
        nodes = self._get_descendants_for(0, True)
        expected = set(self.nodes)
        self.assertEqual(nodes, expected)

    def test_get_descendants_full_tree_no_self(self):
        nodes = self._get_descendants_for(0, False)
        expected = set(self.nodes) - set([self.nodes[0]])
        self.assertEqual(nodes, expected)

    def test_get_descendants_sub_tree(self):
        nodes = self._get_descendants_for(1, True)
        expected = set([self.nodes[1], self.nodes[3], self.nodes[4]])
        self.assertEqual(nodes, expected)

    def test_get_descendants_sub_tree_no_self(self):
        ous = self._get_descendants_for(1, False)
        expected = set([self.nodes[3], self.nodes[4]])
        self.assertEqual(nodes, expected)
```

**Comment by matthiask** [comment]
Yes, the `refresh_from_db` call is necessary. This issue tracker is full of variations of this particular problem (https://github.com/django-mptt/django-mptt/issues?q=is%3Aopen+is%3Aissue+label%3A%22Broken+Tree%22) — closing therefore. Thanks for the report!
