### ISSUE TITLE
pip install creates tests folder in site-packages

### ISSUE THREAD

**Issue by bertini36** [django-mptt/django-mptt#453]
When install your package via pip inside site-packages folder creates two folders, your mptt folder and another named tests (that is your tests folder). So when importing from our project we have a name collision with our tests folder.
mptt shouldn't create tests folder in site-packages :)

Thank you

**Comment by craigds** [comment]
How do other packages fix this? Is the best approach to not include tests at all?

**Comment by bertini36** [comment]
I think that the best solution is put the tests folder inside mptt folder if you want to distribute your tests or the same way that you do now but not distribute the tests.
