### ISSUE TITLE
DraggableMPTTAdmin and list_editable bug

### ISSUE THREAD

**Issue by brupelo** [django-mptt/django-mptt#465]
I've started using django-mptt today and I've seen there is a little [bug](http://screencast.com/t/oGm8uZ2bBk) when you define some fields as editable in some modelAdmin inheriting from DraggableMPTTAdmin, is it easy to fix?

Thanks.

**Comment by matthiask** [comment]
Ah, the autocompletion field somehow isn't repositioned when collapsing/expanding the tree.

Not sure whether this is easy to fix — does not sound too hard, but you never know in advance.

**Comment by brupelo** [comment]
Sure... and not only that, imho when you're editting a field (using arrow keys) the tree shouldn't collapse/expand... Otherwise it becomes pretty annoying editing stuff, you become dizze :-)

**Comment by matthiask** [comment]
An easy fix :) thanks for the report!
