### ISSUE TITLE
Unique constraint failure when moving nodes

### ISSUE THREAD

**Issue by olivierdalang** [django-mptt/django-mptt#466]
Hi !

I have a MPTT tree with an unique constraint on the parent and a "code" field. With such a setup, I get an IntegrityError when I reparent a child if there's already a child with the code, **even if I change the code so that they don't conflict** !

This means I need to change the code, save, then reparent, and save again. This also means I'll get headaches if the new code is conflicting in the initial parent.

I'm surprised to find a bug with a setup that seems extremely common (wanting an unique property per parent). Did I miss something ?

Anyway, thanks a lot for the tool !

Here's the model I tested with :

``` python
class TestModel( MPTTModel ):
    class Meta:
        unique_together = (('parent','code',),)
    parent = TreeForeignKey('self', null=True)
    code = models.CharField(max_length=10)
```

And here's the steps to reproduce

``` python
from MyApp.models import TestModel
a = TestModel.objects.create(code='a',parent=None)
b = TestModel.objects.create(code='b',parent=None)
a1 = TestModel.objects.create(code='1',parent=a)
b1 = TestModel.objects.create(code='1',parent=b)

b1.code = '2'
b1.parent = a
b1.save() # THIS THROWS IntegrityError: UNIQUE constraint failed
```

**Comment by olivierdalang** [comment]
I forgot to give the details :
mptt 0.8.4
django 1.9.6

**Comment by olivierdalang** [comment]
And also note that in the admin, when having a Unique constrain violation, you get a nice error message (`Please correct the error below. Test model with this Parent and Code already exists.`), while here the exception isn't catched...

**Comment by craigds** [comment]
Thanks for the report. mptt doesn't do anything special with unique constraints, and doesn't touch non-mptt attributes (like `code`) so I don't see how mptt could affect this really.

That said... to confirm that, could you please post the database queries involved, so we can tell what's going on? i.e. `connection.queries` (assuming `DEBUG` is on)

**Comment by olivierdalang** [comment]
@craigds Here are the queries generated by the save() line (sqlite, but same occurs on postgres).
Clearly, mptt tries to update parent_id without updating the other fields (code...), leading to the constraint violation.

See my PR providing tests for this issue : https://github.com/django-mptt/django-mptt/pull/467

```sql

UPDATE "MyApp_testmodel"
SET "lft" = CASE
        WHEN "lft" > 3
            THEN "lft" + 2
        ELSE "lft" END,
    "rght" = CASE
        WHEN "rght" > 3
            THEN "rght" + 2
        ELSE "rght" END
WHERE "tree_id" = 1
  AND ("lft" > 3 OR "rght" > 3)

UPDATE "MyApp_testmodel"
SET "level" = CASE
        WHEN "lft" >= 2 AND "lft" <= 3
            THEN "level" - 0
        ELSE "level" END,
    "tree_id" = CASE
        WHEN "lft" >= 2 AND "lft" <= 3
            THEN 1
        ELSE "tree_id" END,
    "lft" = CASE
        WHEN "lft" >= 2 AND "lft" <= 3
            THEN "lft" - -2
        WHEN "lft" > 1
            THEN "lft" - 2
        ELSE "lft" END,
    "rght" = CASE
        WHEN "rght" >= 2 AND "rght" <= 3
            THEN "rght" - -2
        WHEN "rght" > 1
            THEN "rght" - 2
        ELSE "rght" END,
    "parent_id" = CASE
        WHEN "id" = 4
            THEN 1
        ELSE "parent_id" END
WHERE "tree_id" = 2
```

And here's the stack trace
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/mptt/models.py", line 927, in save
    self, parent, 'last-child', save=False)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/mptt/managers.py", line 71, in wrapped
    return method(self, *args, **kwargs)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/mptt/managers.py", line 591, in _move_node
    self._move_child_node(node, target, position)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/mptt/managers.py", line 1014, in _move_child_node
    self._move_child_to_new_tree(node, target, position)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/mptt/managers.py", line 1039, in _move_child_to_new_tree
    node, level_change, left_right_change, new_tree_id, parent.pk)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/mptt/managers.py", line 852, in _inter_tree_move_and_close_gap
    cursor.execute(inter_tree_move_query, params)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/olivier/virtualenvs/Test/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: MyApp_testmodel.parent_id, MyApp_testmodel.code```

**Comment by craigds** [comment]
Thanks for that. Yes, that makes sense now.

One way to solve this would be to wrap `save()` in a `transaction.atomic` block, and use something like `SET CONSTRAINTS ALL DEFERRED` to prevent the unique constraint from triggering until the transaction commits (the `save` will change the `code` value to the correct value _just_ after this.)

That's probably postgres-specific though; I'm not sure how that affects other databases. Also, it might be too magic a thing to include (IME `save` isn't _normally_ wrapped in a transaction)

**Comment by olivierdalang** [comment]
I'm not familiar with django-mptt's internals, but another way I see would be to remove parent_id from the second query, as it should be set by the model's save method anyway. I'm not sure if it's used in other cases though (batch reparenting...)

**Comment by craigds** [comment]
That does seem like a saner solution 😄

**Comment by cristianocca** [comment]
I have had a similar issue, where a node has a unique constraint, and moving this node from one tree to another while at the same time having that field updated would cause a unique exception because the move operation would happen with the old value. Also saving first wouldn't work because that new value might cause a unique exception on the current tree, so I basically need to make the value nullable, set it to null so I'm sure unique constraints won't fail anywhere and then when the node movement is completed, set the new value.

Any better approaches that do not require database specific queries?

**Comment by matthiask** [comment]
@cristianocca @olivierdalang I opened a pull request (#486) containing a proposed solution to this problem. Would be awesome if you find the time to have a look at the code, and maybe send some feedback either on the pull request or on the mailing list (https://groups.google.com/forum/#!topic/django-mptt-dev/BspVX1DdGHk)

**Comment by cristianocca** [comment]
@matthiask The changes to fix this would be on this commit?

If I'm understanding correctly, the change was to add a model save before doing the move operations? I don't think that will fix all the cases.
It will prevent issues on the target tree, but the source tree might raise a conflict if the new value is invalid in the source tree and you attempt to save it before doing the move operation. I think the tests are not considering that case as well.

The only fix is to make sure both the parent and all unique_together constraints keys are updated at the same time in the same query and not the keys first and then the parent or the other way around.

**Comment by matthiask** [comment]
The new code is more careful to either only modify the mptt bookkeeping attributes (lft,rght,level,tree_id) OR all other fields (i.e. parent and unique key fields).

So, as long as unique_together does not contain any mptt bookkeeping attributes things should work now. The tests proposed by Olivier (https://github.com/matthiask/django-mptt/commit/2ebc03d47631dc894103cd8595ec3e4d64f08132) pass now.

**Comment by cristianocca** [comment]
Maybe I'm not understanding completely, but the test doesn't really test the case I said above. And also the code changes from https://github.com/django-mptt/django-mptt/pull/486/commits/dd6ea7de7e31a2e4fa0f6992c81feb4bf287b226 doesn't seem to prevent it either, but again I'm probably wrong since I don't really know the code.

The one example that currently crashes is this (following the test code)
```
a = UniqueCodePerParentModel.objects.create(code='a', parent=None)
b = UniqueCodePerParentModel.objects.create(code='b', parent=None)    
a1 = UniqueCodePerParentModel.objects.create(code='1', parent=a)
a2 = UniqueCodePerParentModel.objects.create(code='2', parent=a)

b1 = UniqueCodePerParentModel.objects.create(code='1', parent=b)

a1.parent = b
a1.code = '2'

a1.save()    
```

Right now it crashes because it first tries to do the parent update, while keeping the old value for code (even if it was changed on the model). However, if the force a save first to only save the code value, a similar error will happen. The actual operation should be saving both parent and code in the same query. Is this the actual new behaviour? Can you try adding the above code as a test?

**Comment by matthiask** [comment]
Well, yes. I already did that in the pull request mentioned above:

https://github.com/django-mptt/django-mptt/pull/486/files#diff-fac85e7dd7822df3b1bb3edc1f1f963dR2044 

The fix is contained in the commit https://github.com/matthiask/django-mptt/commit/dd6ea7de7e31a2e4fa0f6992c81feb4bf287b226 — first, lft/rght/level/tree_id are updated, and then code and parent in the same query (using the standard `save()` method)

**Comment by cristianocca** [comment]
Excellent! I didn't understand things were being saved in that order.

**Comment by olivierdalang** [comment]
@matthiask I wanted to know what actions I should take to have this issue fixed. I'm not sure I understand well what the pr #486 is about ? It is not only addressing this issue, right ? Would it be possible to apply the commit you are mentionning ?

**Comment by olivierdalang** [comment]
I opened PR #548 to fix this. Let me know if I can do anything else to get this merged ;) Thanks for the great work !
