### ISSUE TITLE
Order of insertion causes new roots to get the same tree_id when order_insertion_by is defined

### ISSUE THREAD

**Issue by cmermingas** [django-mptt/django-mptt#470]
Using `django-mptt 0.8.4`

With this model:

```
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

class Node(MPTTModel):
    name = models.CharField(max_length=50)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    class MPTTMeta:
        order_insertion_by = ['name']
```

And these tests:

```
from django.test import TestCase
from .models import Node


class NodeTest(TestCase):
    def test_multiple_roots_in_order(self):
        r1 = Node.objects.create(name='A', parent=None)
        r2 = Node.objects.create(name='B', parent=None)

        self.assertNotEqual(r1.tree_id, r2.tree_id)

    def test_multiple_roots_in_reverse_order(self):
        r1 = Node.objects.create(name='B', parent=None)
        r2 = Node.objects.create(name='A', parent=None)

        self.assertNotEqual(r1.tree_id, r2.tree_id)
```

When the nodes are inserted "in order" (A before B), they go into separate trees. When the nodes are inserted in reverse order, they go into the same tree:

```
Creating test database for alias 'default'...
.F
======================================================================
FAIL: test_multiple_roots_in_reverse_order (my_app.tests.NodeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cmermingas/django_projects/mptt_test/my_app/tests.py", line 16, in test_multiple_roots_in_reverse_order
    self.assertNotEqual(r1.tree_id, r2.tree_id)
AssertionError: 1 == 1

----------------------------------------------------------------------
Ran 2 tests in 0.007s

FAILED (failures=1)
Destroying test database for alias 'default'...
```

If someone is willing to coach me a bit, I am willing to create a pull request and work on this.

Please let me know if I am doing something wrong. I'm pretty new here.
- Edited: I had a "suspected problem" and a potential fix here. I removed it after discovering that I was totally wrong.

**Comment by cmermingas** [comment]
I went through `django-mptt` test suite and I saw this scenario covered there in a slightly different way. So, I tried it again like this:

```
class NodeTest(TestCase):
    def test_multiple_roots_in_order(self):
        r1 = Node.objects.create(name='A', parent=None)
        r2 = Node.objects.create(name='B', parent=None)

        nodes = Node.objects.all()

        self.assertNotEqual(nodes[0].tree_id, nodes[1].tree_id)

    def test_multiple_roots_in_reverse_order(self):
        r1 = Node.objects.create(name='B', parent=None)
        r2 = Node.objects.create(name='A', parent=None)

        nodes = Node.objects.all()

        self.assertNotEqual(nodes[0].tree_id, nodes[1].tree_id)
```

In this case it works fine, which is reassuring and I can make progress. However, it continues to be confusing. Maybe the `create()` method could return the actual object from the DB? Or maybe a more generous explanation in the docs?

**Comment by matthiask** [comment]
Both methods actually return the object from the DB *at the time the statement was executed*.

Django's models (and in extension mptt's models) are not automagically updated when the database contents change. If you're working with django-mptt and are not sure whether the instance data is current, better always run `refresh_from_db` (https://docs.djangoproject.com/en/1.9/ref/models/instances/#django.db.models.Model.refresh_from_db) before doing anything with the instance, be it reading (resulting in wrong values) or writing (potentially resulting in a corrupted tree)

That being said, the docs should probably contain this recommendation.

**Comment by mpasternak** [comment]
Hi, 

@matthiask , I was just hit by a similar problem. Doest it look like the same problem to you? Do you have any ideas, how should I tackle this? 

My scenario (it is already in my branch here: https://github.com/mpasternak/django-mptt )

```
class OrderedInsertionSortingTestCase(TestCase):
    def test_proper_cache_reloading(self):
        root = OrderedInsertion.objects.create(name="")
        b = OrderedInsertion.objects.create(name="b", parent=root)
        a = OrderedInsertion.objects.create(name="a", parent=root)

        a_ancestors = a.get_ancestors(include_self=True)
        b_ancestors = b.get_ancestors(include_self=True)

        assert a in a_ancestors
        assert b in b_ancestors

        assert a not in b_ancestors
        assert b not in a_ancestors

```

This will fail:

```
======================================================================
FAIL: test_proper_reloading (tests.myapp.tests.OrderedInsertionSortingTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mpasternak/Programowanie/django-mptt/tests/myapp/tests.py", line 969, in test_proper_reloading
    assert b in b_ancestors
AssertionError

----------------------------------------------------------------------
```

**Comment by mpasternak** [comment]
EDIT: I understand the source of the problem. I should ``b.refresh_from_db()`` right after adding ``a``. 

I'll try to document this in my branch.

**Comment by mpasternak** [comment]
@matthiask done, please review.

**Comment by mpasternak** [comment]
You're the best! 👍
