### ISSUE TITLE
Don't publish 'tests' as a separate package..

### ISSUE THREAD

**Issue by iljamaas** [django-mptt/django-mptt#472]
The distributed  django-mptt packages contain a '**tests**' directory which, when installed, is a top-level site-package, which can easily conflict with other package (doing the same thing ... )

I think the tests should either be NOT included in the packages, OR, be put inside the django-mptt package to prevent conflicts.

**Comment by matthiask** [comment]
Thanks for the report! This is a duplicate of #453.
