### ISSUE TITLE
django 1.10 'Options' object has no attribute 'concrete_managers'

### ISSUE THREAD

**Issue by burakk** [django-mptt/django-mptt#473]
Hi,

I am getting 'Options' object has no attribute 'concrete_managers'  error when i try to run my project.

Note:
I have modified models.py  as said in issue #469

Error is as:
...    cls = meta.register(cls)
  File "/Users/burakk/BurakWorks/Web/VIRTUAL_ENVIRONMENTS/python3.5.0_pikto_web_dj_1_10/lib/python3.5/site-packages/mptt/models.py", line 348, in register
    cls_managers = cls._meta.concrete_managers + cls._meta.abstract_managers
AttributeError: 'Options' object has no attribute 'concrete_managers'

**Comment by matthiask** [comment]
Thanks for the report. Here's my pile of hacks containing a possible fix for this issue: https://github.com/matthiask/django-mptt/commit/4dabf23c44c517675ca6eb94416ade30d745f36e
