### ISSUE TITLE
Django itself shouldn't be referenced in install_requires

### ISSUE THREAD

**Issue by andybak** [django-mptt/django-mptt#475]
#3 Fixed this back in 2010 but it seems to have crept back in for some reason.

**Comment by matthiask** [comment]
The current `install_requires` entry has its roots in 9fb26276c44747479925d31053988deaf24d9849. 

I find it somewhat useful to communicate the supported versions of Django, but don't care much either way. Opinions?

(django-registration does not depend on Django; the official tutorial for writing reusable apps does not include install_requires either - https://docs.djangoproject.com/en/1.9/intro/reusable-apps/ )

**Comment by andybak** [comment]
Thanks. For the record it seems to cause me lots of problems with pip doing unexpected and unwanted upgrades to Django when I'm trying to upgrade something unrelated.
