### ISSUE TITLE
Question about indexes

### ISSUE THREAD

**Issue by cristianocca** [django-mptt/django-mptt#476]
Hello there, this is mainly a question/suggestion.

It seems that the fields for "lft", "rght", "tree_id" and "level" have a index added to them, and also you probably want to add an additional index on the parent relation (this is added by the developer and not automatically by mptt if I'm not wrong)

Now this seems like quite a hell lot of indexes, performance will probably get hit a bit. Looking at the created queries for queries like get_descendants and similar, they are all based on tree_id as the main field and then other values are used. This means the database will most of the time use the tree_id index as this will be the most selective one as well, because left, right and level will have their own values for each tree, so they will be quite big and never used.

Wouldn't it better for the indexes to be all pairs prefixed with tree_id? Are all of them really needed? I'm sure that an index on (tree_id, lft) and (tree_id, rght) will probably be way better than the 3 separated indexes, at least for the get_descendants query.

As I see it, most if not all queries will always be based on a given tree, so it makes sense to have all indexes prefixed with tree_id so the query optimizer can use it and gain an additional plus being able to use the second part of the index such as lft or right.

I haven't tested all queries generated by mptt, I hope someone more related to the implementation could shine some light on this, and if changing the indexes would really help or not.

**Comment by craigds** [comment]
You're probably right, and these two indices would probably do the trick:
```
        index_together = [
            ("tree_id", "lft", "rght"),
            ("tree_id", "rght"),
        ]
```
(though with those field names populated from `_mptt_meta`)

To make this change I think we'd need a sensible way to generate migrations, and preferably including `rebuild()`. (related tickets #382, #195). I'd love to solve the migration issue since it trips people up all the time.

**Comment by cristianocca** [comment]
I believe it should be no issue on other DB's.
Is the "level" column not a candidate for an index then (still including tree_id)? Considering it is currently indexed. I'm curious in what queries level is used for and if an index would really help

**Comment by matthiask** [comment]
We're using `level` all the time to generate menus — we're seldom interested in more than two levels at a time. `level__range` is perfect for that.

**Comment by matthiask** [comment]
Indexes have been changed in the meantime.
