### ISSUE TITLE
Broken links in README: again )

### ISSUE THREAD

**Issue by yogggoy** [django-mptt/django-mptt#480]
Trees in SQL - move to - [http://www.ibase.ru/files/articles/programming/dbmstrees/sqltrees.html](http://www.ibase.ru/files/articles/programming/dbmstrees/sqltrees.html)
`Managing Hierarchical Data in MySQL`_ - It was found on author personal website -[http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/](http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/)
----edit----
sorry, incorrectly inserted links. now all ok

**Comment by matthiask** [comment]
Thanks!
