### ISSUE TITLE
Filter __in

### ISSUE THREAD

**Issue by Six-wars** [django-mptt/django-mptt#487]
I'm trying to do a filter for with a model with TreeManyToManyField but I get the error 
TypeError: 'Category' object is not iterable

trending = Category.objects.get(id=312)
In [28]: trending
Out[28]: <Category: Lifestyle >> Trending Topics>

listy = Article.objects.filter(categories__in=trending)

**Comment by matthiask** [comment]
What are you trying to achieve? Do you want to fetch all articles in trending and its descendants?

`Article.objects.filter(categories__in=trending.get_descendants(include_self=True))`

(`__in` requires an iterable or a queryset, and Django model instances are neither.)

(Closing — this seems to be a simple usage question. Please reopen if there's an issue with django-mptt.)
