### ISSUE TITLE
Show child from linked mptt table in django

### ISSUE THREAD

**Issue by ohid1986** [django-mptt/django-mptt#492]
I have created django-mptt table which gave following tree view:
```
Group-1 0
    Ministry A 1
        Division A 2
        Division B 2
        Division C 2
    Ministry B 1
    Ministry C 1
        Division D 2
        Division E 2
    Ministry D 1
Group-2 0
    Ministry E 1
        Division G 2
        Division Z 2
    Ministry F 1
        Division I 2
        Division J 2

```
Here 0,1,2 are node level.

Here is my Sitting model:

```
class Sitting(models.Model):
    sit_date = models.DateField(blank=False)
    cut_off_date = models.DateField(null=True, blank=True)
    ballot_date = models.DateField(null=True, blank=True)
    sess_no = models.ForeignKey(Session,
                                 on_delete=models.CASCADE)
    genre = TreeForeignKey('Genre', null=True, blank=True, db_index=True)
```
This is my views.py:

```
def show_genres(request):
    return render(
        request,
        'genre/genres.html',
        {'nodes':Genre.objects.all()},)

def sitting_list(request):
    return render(
        request,
        'genre/sitting_list.html',
        {'sittings': Sitting.objects.all()}, )
```
my templates:

```
 <table>
        <tr>
      <th>Sitting Date</th>
      <th>Group No</th>        
        </tr>        
        {% for sitting in sittings %}
        <tr>
           <td> {{ sitting }}</td>
            <td>{{sitting.genre}}</td>
     </tr>
        {% endfor %}        
    </table>

```
My sitting output:
```
Sitting Date    Group No
2016-08-31     Group-1
2016-09-01     Group-2
```

But I want to show all descendants(i.e. level 1(e.g., Ministry A) and level 2(e.g., Division A)) instead of level 0 (e.g., Group-1)

How I to I do that?

**Comment by matthiask** [comment]
The simplest thing (but maybe with bad performance) would be to iterate over `sitting.genre.get_descendants` (`{% for genre in sitting.genre.get_descendants %}...{% endfor %}`) in the template. If there are many sittings you'd have to prefetch the descendants somehow, or cache the output to get acceptable performance, but that depends on your use case.

Or did I miss something? If I did please provide an example of the output you'd want, not the output you're currently getting.

**Comment by matthiask** [comment]
I think this is an usage question. Please reopen if there's an issue in django-mptt, or something which should be documented better.

Thanks!

**Comment by ohid1986** [comment]
Sorry for late reply. 

Here is my new template:

```
{% block content %}
<table>
    <tr>
  <th>Sitting Date</th>
  <th>Group No</th>

    </tr>
    {% for sitting in sittings %}
    <tr>
       <td> {{ sitting }}</td>
    {% for genre in sitting.genre.get_descendants %}

       <td> {{ genre }}</td>

        {% endfor %}
         <p>(Ballot: {{ sitting.ballot_date}})</p>
    </tr>
    {% endfor %}
</table>
{% endblock %}

``` Here is my view file:
```
def sitting_list(request):
    sitting=Sitting.objects.all()
    nodes = Genre.objects.select_related('parent')
    return render(
        request,
        'genre/sitting_list.html',
        {'sittings':sitting, 'nodes':nodes},  )

```
This gave output as 
```
(Ballot: Aug. 19, 2016)
(Ballot: Aug. 20, 2016)
Sitting Date 	Group No
2016-08-31 	Ministry A 	Division A 	Division B 	Division C 	Ministry B 	Ministry C 	Division D 	Division E 	Ministry D
2016-09-01 	Ministry E 	Division G 	Division Z 	Ministry F 	Division I 	Division J 
```
My desired output will be:

![selection_003](https://cloud.githubusercontent.com/assets/14290896/17460775/6c9b4178-5c95-11e6-82ea-7ec1a4e95aa0.png)

Here Ministry name only come when there is no division exists else only division name show.
I hope you help me to get my desired output.
