### ISSUE TITLE
add 'mptt' in INSTALLED_APPS

### ISSUE THREAD

**Issue by Zverushko** [django-mptt/django-mptt#493]
Then i add this str in list a got error:
http://pastebin.com/VjwBxhZW
https://yadi.sk/i/GVl0i-fatwntn

**Comment by ad-m** [comment]
See #488, #469.

**Comment by Zverushko** [comment]
thx! https://github.com/django-mptt/django-mptt/issues/469#issuecomment-224292821 work for me

**Comment by matthiask** [comment]
Closing, since this is a duplicate. Thanks for the report!
