### ISSUE TITLE
Models with multiple tree managers

### ISSUE THREAD

**Issue by randlet** [django-mptt/django-mptt#499]
While trying to upgrade to Django 1.9 and MPTT 0.8.5 from Django 1.8 and MPTT 0.7.0 I ran into some MPPT behaviour that I found very confusing.  Finally today I tracked down the issue.  We have a model with two TreeManager's on it like so:

```
class FooObjects(TreeManager):
    def get_queryset(self):
        return super(FooObjects, self).get_queryset().exclude(foo='')

class Bar(MPTTModel):
    parent = models.ForeignKey('self', related_name="children", ...)
    bar = CharField(...)
    foo = CharField(...)

    objects = TreeManager()
    foo_objects = FooObjects()

```

This worked fine in MPTT 0.7.0 but when upgrading to 0.8.5 weird things like this would happen:

```
bar1 = Bar.objects.create(bar="b1", foo='')
bar2 = Bar.objects.create(bar="b2", foo='')
bar3 = Bar.objects.create(bar="b3", foo='')

bar2.parent = bar1
bar2.save()
bar3.parent = bar1
bar3.save()

# this  should have created a parent (f1) with two children (f2, f3)

bar1.refresh_from_db()
bar2.refresh_from_db()
bar3.refresh_from_db()

bar2.parent # bar1
bar3.parent # bar1
bar1.get_children() # empty list !
bar1.get_ancestors() # empty list !
bar1.children.all() # [<bar2>, <bar3>] !!!

```

Eventually I figured out that the `_tree_manager` attribute of the `Bar` class was being set to `Bar.foo_objects` rather than `Bar.objects` as I was expecting.

`MPTTModelBase` [decides what to use as the _tree_manager_attribute](https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L337-L360) based on the first instance of a `TreeManager` it finds in the list of `cls._meta.concrete_managers + cls._.meta.abstract_managers`.  Looking at `Bar._meta.concrete_managers` I found `[(35, 'foo_objects', <FooObjects>), (34, 'objects', <TreeManager>), (36, '_base_manager', <django.db.models.manager.Manager>)]` which explains why `_tree_manager` is set to `FooObjects` rather than `objects` as expected.

As a hacky workaround you can simply do the following:

```
class Bar(MPTTModel):
        ...

Bar._tree_manager = Bar.objects
```

or

```
class Bar(MPTTModel):
    ...
    __getattribute__(self, attr):
        if attr == "_tree_manager":
            return Bar.objects
        return super(Bar, self).__getattribute__(attr)
```

but neither of those is ideal from a future proofing perspective.

All of this to say, it would be great if at a minimum this was documented somewhere or even better if we could specify what the default tree manager should be.  Checking if `cls._default_manager` is an instance of `TreeManager` before falling back to `cls._meta.concrete_managers + cls._meta.abatract_managers` would probably work well too.

**Comment by randlet** [comment]
Happy to work up a pull request for this with a bit of guidance on what the best approach to take is (if any!).

**Comment by craigds** [comment]
Can you try this with just-released 0.8.6? I suspect it has been fixed.

**Comment by randlet** [comment]
The same problem exists on 0.8.6 unfortunately.

**Comment by sephii** [comment]
My PR checks for `cls._default_manager` and then falls back to the first `TreeManager` found (sorting them by creation order, which was missing in the original code). I think that's the correct way to do it.
