### ISSUE TITLE
Disable moving based on permissions 

### ISSUE THREAD

**Issue by frague59** [django-mptt/django-mptt#510]
Hi, 

I've implemented a Tree using MPTT. 
Some users can see a part of the tree, and some can see the whole tree. I use DragableMPTTAdmin to display this tree in the admin...

Is it possible to disable the "move" functionalities, based on permissions ?

I've tryed to override the tree_actions method, but it does not know about the request, which could provide me the user.

Thanks for your great tool !

**Comment by matthiask** [comment]
The `_move_node` method runs `has_change_permission` on the item to be moved. If this method returns `False` the move does not happen. (https://github.com/django-mptt/django-mptt/blob/master/mptt/admin.py#L223)

There is no way to hide the move icon only for some rows right now.

**Comment by frague59** [comment]
Hi, 

I've overridden the `get_list_display(self, request)` method to hide / display the `tree_actions` field from the `list_display`, base on my user, which seems to be the right method...
