### ISSUE TITLE
PR #491 broke raw_id_fields on Django 1.9 and below

### ISSUE THREAD

**Issue by yakky** [django-mptt/django-mptt#536]
Changes in #491 broke the related selection from raw_id_fields by adding Django 1.10-only syntax (``data-popup-opener``).
The old ``onclick="opener.dismissRelatedLookupPopup(window, &#39;%s&#39;); return false;"`` syntax should be present for lower django versions

**Comment by yakky** [comment]
I can provide a PR, I just need an advice how to do django-version detection according to the project code style

**Comment by craigds** [comment]
This was fixed by #537, closing
