### ISSUE TITLE
django 1.11 supported new release

### ISSUE THREAD

**Issue by auvipy** [django-mptt/django-mptt#564]

**Comment by goodtune** [comment]
This is the only open issue in for the 0.9 milestone – I think this could be closed and a 0.9 version cut, there hasn't been a new release since December last year.

The `master` branch is currently compatible with 1.11 and also the 2.0 beta, can we get a new build on pypi?

**Comment by djowett** [comment]
+1

**Comment by chinskiy** [comment]
+1

**Comment by claudep** [comment]
Django 2.0 is due to be released December 1st. A django-mptt release would be very nice to have by that date.

**Comment by zw3n** [comment]
New issue for django 2.0 support: #613

**Comment by craigds** [comment]
I've released 0.9.0.
