### ISSUE TITLE
Unable to call {% cycle %} by name 

### ISSUE THREAD

**Issue by Jives7** [django-mptt/django-mptt#572]
I have the following cycle in my template. Line 3 correctly cycles and returns the next value, but referring to the cycle by name (counting) does not return anything. Placing the cycle outside of the for loop and referencing it by name within the loop just causes it to always output the first value.

```
{% for r,structure in tree|tree_info %}
            {% if structure.new_level %}
                Cycle: {% cycle 1 2 3 4 5 6 7 as counting %}
            {% else %}
                {{ counting }}
            {% endif %}
{% endfor %}
```

**Comment by matthiask** [comment]
Please explain what you want to do. Do you want to output the level of nodes?

**Comment by matthiask** [comment]
{% cycle %} is a Django tag, not a django-mptt tag.
