### ISSUE TITLE
Hierarchical urls

### ISSUE THREAD

**Issue by dg1980** [django-mptt/django-mptt#585]
Hi Guys, 

I'm trying to achieve hierarchical urls with access to specified objects in tree (for an example: /category/ gives category object in tree, /category/subcategory/ gives subcategory object in tree etc.). Unfortunately I did not find any working solution. I have tried packages like django-mptt-urls or django-clean-urls, but they don't work with Django 1.11. 

This topic has been repeatedly discussed. However, I did not find the right, clean,  pythonic solution.

Do you have any advice how to achieve it?

I will be grateful for your help.

**Comment by matthiask** [comment]
Here's a solution which might work for you?
https://github.com/feincms/feincms/blob/master/feincms/module/page/models.py#L240

**Comment by dg1980** [comment]
Thank's a lot. This solution looks good. 

Yesterday I've made a view function based on re module. URL Dispather passes the entire path to it. Path is subdivided by re into list of object slugs, and then iterates through it. Finally last object in path is returned to view. I was wondering about its performance, but it works really well (even not cached at the moment). 

I will keep in mind mentioned solution from FeinCMS. 

Thank you very much.
