### ISSUE TITLE
Duplicate tree

### ISSUE THREAD

**Issue by gabrielfast** [django-mptt/django-mptt#590]
Hello,

How do I duplicate a tree with new tree_id?

Thanks

**Comment by matthiask** [comment]
You mean something like this?

```
id_map = {None: None}
for node in Node.objects.filter(tree_id=old_id):
    old_pk = node.pk
    node.pk = None
    node.parent_id = id_map[node.parent_id]
    node.save(force_insert=True)
    id_map[old_pk] = node.pk
```

If this does not work, try asking again on the mailing list: https://groups.google.com/forum/#!forum/django-mptt-dev
