### ISSUE TITLE
When to rebuild and/or reload to avoid corrupt trees with bulk creates

### ISSUE THREAD

**Issue by joinghel** [django-mptt/django-mptt#598]
Hey guys,

This is more a question than an issue, but I can't find any clarity in the docs or code. I'll try to explain this using an example based on the docs. Assume I have the  `Genre` class and I do the following operations:

    rock = Genre.objects.create(name='B')
    metal = Genre.objects.create(name='C')
    metal.parent = rock
    metal.save()

    # Now add a Genre which comes before the others due to ordering on name
    classic = Genre.objects.create(name='A')
        
    # Get the ancestors of metal, including metal
    ancestors = metal.get_ancestors(ascending=True, include_self=True)

What happens: `metal` has no ancestors. In fact, even `metal` is not in `ancestors` even though `include_self=True`.

What I tried:
- Added `Genre.objects.rebuild()` after the creates: makes no difference. So should I do this?
- Added `metal.refresh_from_db()` after the creates: makes no difference.
- Refreshed all Genre objects: **this works**

Took me a while to figure out I had to reload the objects. So my questions: 
- Am I doing something wrong?
- Will this happen when I have a CreateView and I call `get_ancestors` in a different view?

This actually happened while creating objects in `setUp()` during unit tests and directly calling `get_ancestors` to verify a method on my model. So normally this does not happen in my code, but I'd still like to know if I should add extra checks.

I currently handle this like this (to be notified rather than doing wrong stuff):

    ancestors = metal.get_ancestors(ascending=True, include_self=True)
    if not ancestors:
        raise EmptyResultSet

Thank you very much!

**Comment by matthiask** [comment]
You'll have to reload/refresh real often. Alternatively, you could help test https://github.com/django-mptt/django-mptt/pull/575 -- this should make bulk inserts much much faster and also safe(r).

**Comment by joinghel** [comment]
Ok thanks! Good to know that it's necessary to reload/refresh. I'll try and see if I can add something usefull to that PR.
