### ISSUE TITLE
RemovedInDjango20 warning class is actually removed in Django 2.0

### ISSUE THREAD

**Issue by canni** [django-mptt/django-mptt#610]
Import of `RemovedInDjango20` warning class fails when actually using Django 2.0, because this warning class is no longer there :)

**Comment by canni** [comment]
NVMD, I see that master branch has this one fixed now

**Comment by vtbassmatt** [comment]
Will there be a release soon? (And thanks for your work on this package! I use it for a hierarchical list of places in a small, personal webapp.)
