### ISSUE TITLE
How to change default behavior of django-mptt?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [django-mptt/django-mptt#620]
First of all THANKS for this project! I have 2 questions.

By default django-mptt create fields like: `lft, rght, level, tree_id` in database.

1) Is it possible don't create fields like `lft, rght`? I dont need them cause I dont use these fields.
2) Is it possible to rename `tree_id` to other name? For example: `position`.

It seems to me that only available solution is to change `0001_initial.py` file before `migrate` command. What can you advice to me?

**Comment by matthiask** [comment]
1. No, this is not possible with django-mptt.
2. Yes: https://django-mptt.readthedocs.io/en/latest/models.html#model-options (Although I would not recommend doing this, because removing those model options would simplify the code of django-mptt quite a bit.)

**Comment by NogerbekNurzhan** [comment]
Thank you for your answers, bro! :)
I have one more question about this default fields. After your answer I will close the question. 

Is it possible in `models.py` file set `blank=True, null=True` setiings to `lft, rght` fields?

**Comment by matthiask** [comment]
No, the code isn't prepared for this, and also, mptt expects that the values of lft and rght make some sense.

If you need to add many nodes to the tree, you might want to take a look at #444.

**Comment by NogerbekNurzhan** [comment]
I use tree structure in template. When I changed `lft, rght` fields values in database it didn't affect to tree. Tree was fine in template. I think we need `lft, rght` in Django admin, right?
