### ISSUE TITLE
Quick search

### ISSUE THREAD

**Issue by bylli79** [django-mptt/django-mptt#621]
Hello,
how can I use this type of search (/root/path1/path2../path n) to get to the node?
Do I have to use cycles or is there a faster way?

Thank you

**Comment by mikekeda** [comment]
What do you mean by "path"?

**Comment by bylli79** [comment]
By path I mean that of a file system

**Comment by mikekeda** [comment]
I didn't get it.
Node is stored in db, how it's related to a file system?

**Comment by matthiask** [comment]
The same question was already asked in #585. Hopefully this helps.

**Comment by bylli79** [comment]
thanks!
