### ISSUE TITLE
Error migrate

### ISSUE THREAD

**Issue by bylli79** [django-mptt/django-mptt#623]
For some tests I used this code
class test (MPTTModel):
     name = models.CharField ()
     parent = TreeForeignKey ('self', null = True, blank = True,
                             related_name = 'children', db_index = True,
                             on_delete = models.CASCADE)

When I run this command
python3.6 manage.py makemigrations test_app

I get the following error:

django.db.utils.ProgrammingError: ERROR: the "test_app_test" relationship does not exist
LINE 1: ... "tree_id", "test_app_test". "Level" FROM

tree_id, should not be created automatically?

Thanks :-)

**Comment by matthiask** [comment]
There's no reason why the code you posted would query the database while starting up. The real reason for the problem lies elsewhere, maybe in an eager evaluation of a `test` queryset somewhere.
