### ISSUE TITLE
get_cached_trees -> no such table exception on initial migration

### ISSUE THREAD

**Issue by colindjk** [django-mptt/django-mptt#628]
Using python 3.6

_view.py_
```python
class ExampleHierarchyList(generics.ListAPIView):
    serializer_class = serializers.ExampleHierarchySerializer
    queryset = models.Example.objects.get_cached_trees()
```

I have code that looks somewhat like that (just changed the base name to Example). When I run my _initial_ migrations `python manage.py makemigrations myapp` or just `... migrate myapp`, I get the error `no such table myapp_example`. 

My solution to fix the error was to remove the line 
```python
    queryset = models.Example.objects.get_cached_trees()
```

Then make the necessary migrations, after which point I could add the above line back into the code. A bit jank, but it worked. 

Also wanted to point out that it did seem like a similar issue found in #623. Basically mptt code is executing before the migration actually happens.

**Comment by matthiask** [comment]
This looks very much like executing database queries upon module import, which quite probably isn't what you want.

Isn't there a `get_queryset` method you could override instead of setting the `queryset` attribute?

**Comment by colindjk** [comment]
That fixed it! I'm going to close the issue, but would you happen to know why the `get_cached_trees` wouldn't work, but getting a regular query of the root nodes would work?

Thanks for the help.

**Comment by matthiask** [comment]
Yeah, probably because one query may be evaluated lazily, and the other
cannot.

.filter(parent__isnull=True) vs iterating over the tree and assigning lists
of children to parent nodes.
