### ISSUE TITLE
Proposal: Order entries observe numerical names for MPTTMeta.order_insertion_by

### ISSUE THREAD

**Issue by McCavity** [django-mptt/django-mptt#634]
I'm generating a tree from server positions which have roughly the format:

country / city / provider / room / row / rack / side / position [ / blade server [ / slot ]]

"position" is actually the location inside the rack, i.e. a number between 1 and 48 (slot numbers are affected, too, they range from 1 to 14). This is what my model looks like::

    class Location(MPTTModel, DirtyFieldsMixin, PrintableModel):
    
        class Meta:
            unique_together = ('name', 'parent')
            verbose_name = 'Hardware Device Location'
            verbose_name_plural = 'Hardware Device Locations'
    
        class MPTTMeta:
            order_insertion_by = ['name']
    
        def get_all_fields(self):
            return super(Location, self).get_all_fields(['id', 'created', 'modified'])
    
        def __str__(self):
            return self.name
    
        name = models.CharField(max_length=40, verbose_name='Name')
        location_type = models.CharField(max_length=40, verbose_name='Type', blank=True, null=True)
        parent = TreeForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children', db_index=True, default=None)

as "name" is a CharField, the slots of a blade server get sorted like this::

    1
    10
    11
    12
    13
    14
    2
    3
    ...

Which is perfectly okay for alpahanumeric sorting. However, would it be possible to add a flag to the `MPTTMeta' class that numbers in the name field get sorted numerically?

**Comment by matthiask** [comment]
`order_insertion_by` is passed to `.order_by()` which means that, in the end, the ordering is determined by the database. I don't know whether it would be easily possible to cast the name field to a numeric value and sort by this. 

Is there a reason why you can't just left-pad the names with zeroes? 01, 02, 03, ..., 10, 11 etc. would sort the same way when sorted alphanetically or numerically.

**Comment by McCavity** [comment]
Thanks for your answer. Since other parts of the full parts are completely numberless (like `country`, e.g., which contains values like `Germany`) and others are numbers that may contain special characters (e.g. `room`, may contain values like `3-64`) I can't simply convert them to a numeric value.

What I *can* do, however, is to add a numeric field `name_int` to my model which only gets filled if the value of `name` is an integer - this way I can `order_insertion_by = ['name_int', 'name']` which will have numbered names be sorted by their numeric value first while all other fields have `NULL` in `name_int` which means they will be sorted by `name` just like before.

I could also pad the numbers, yes, but since the `name` field is meant for display in the frontend, I'd rather not, for aesthetic reasons. Thanks again for your time, for my part, I consider this issue closed.

**Comment by McCavity** [comment]
Addendum: Works like a charm. Result of the last run::

    Added: 0
    Updated: 4209
    Skipped: 39048
    Errors: 0

The 4209 updated elements are all rack positions or slot numbers - and in Django's admin interface the new ordering is correct now. For completeness, here's the latest version of my model::

    class Location(MPTTModel, DirtyFieldsMixin, PrintableModel):
    
        class Meta:
            unique_together = ('name', 'parent')
            verbose_name = 'Hardware Device Location'
            verbose_name_plural = 'Hardware Device Locations'
    
        class MPTTMeta:
            order_insertion_by = ['name_int', 'name']
    
        def get_all_fields(self):
            return super(Location, self).get_all_fields(['id', 'created', 'modified'])
    
        def __str__(self):
            return self.name
    
        name = models.CharField(max_length=40, verbose_name='Name', db_index=True)
        name_int = models.PositiveSmallIntegerField(verbose_name='Name (numeric)', blank=True, null=True, db_index=True, default=None)
        location_type = models.CharField(max_length=40, verbose_name='Type', blank=True, null=True, default=None)
        parent = TreeForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, related_name='children', db_index=True, default=None)

And here's the view responsible for filling it::

    def update_location(request):
        extra_content = {}
        if request.method == 'POST':
            form = UpdateLocationForm(request.POST, request.FILES)
            if form.is_valid():
                result_dict = {}
                location_types = ['Room', 'Row', 'Rack', 'Rack Position']
                added = updated = skipped = errors = 0
                decoded_csv = codecs.iterdecode(form.cleaned_data['csv_file'], 'utf-8')
                # skip the first three lines (header lines)
                for index in range(3):
                    next(decoded_csv)
                # process the remaining CSV
                reader = csv.reader(decoded_csv, delimiter=';', quotechar='"')
                for row in reader:
                    # get location relevant entries from CSV row
                    row_items = [row[11], row[12], row[14], row[15]]
                    # split the location string for processing
                    loc_items = row[10].split('/')
                    # search for items starting with "B-" (rear mounted) or
                    # "U-" (front mounted) and split the item in mount side
                    # (front or rear) and the vertical position (rest of item)
                    for item in loc_items:
                        # items starting with 'B-' or 'U-' indicate rack positions
                        # (the remainder is an integer). 'B' is used for rear, 'U'
                        # for front mounted devices.
                        if re.search('^[BU]-', item):
                            sub_items = item.split('-')
                            index = loc_items.index(item)
                            if sub_items[0] == 'B':
                                loc_items[index] = 'Rear'
                            elif sub_items[0] == 'U':
                                loc_items[index] = 'Front'
                            else:
                                raise ValueError('Unknown rack side: %s' % sub_items[0])
                            loc_items.insert(index, sub_items[1])
                    # iterate over the location string's items
                    # and insert them into the Location model
                    index = 0
                    parent = None
                    for item in reversed(loc_items):
                        item_type = None
                        if item == '' and index == 0:
                            item = 'Global'
                        else:
                            try:
                                item_type = location_types[row_items.index(item)]
                            except ValueError:
                                pass
                        try:
                            obj = Location.objects.get(name=item, parent=parent)
                        except Location.DoesNotExist:
                            obj = Location(
                                name = item,
                                parent = parent
                            )
                        if not obj.location_type and item_type:
                            obj.location_type = item_type
                        if item.isdigit():
                            obj.name_int = int(item)
                        # Only save if needed
                        if not obj.id:
                            added += 1
                            obj.save()
                        elif obj.is_dirty():
                            updated += 1
                            obj.save_dirty_fields()
                        else:
                            skipped += 1
                        parent = obj
                        index += 1
                extra_content['result_dict'] = {
                    'Added': added,
                    'Updated': updated,
                    'Skipped': skipped,
                    'Errors': errors
                }
            else:
                extra_content['form'] = form
        else:
            form = UpdateLocationForm()
            extra_content['form'] = form
        return render(request, 'core/update_location.html', extra_content)

It isn't fast, I know, I'd probably be better off doing a bulk update and a `rebuild()` afterwards but time is not an issue - the update is done once a week and once it's started it can happily run on its own.
