### ISSUE TITLE
django-mptt: bugs with multiple databases

### ISSUE THREAD

**Issue by DomHudson** [django-mptt/django-mptt#651]
## Summary
Does django-mptt support multiple client databases? I am not expecting to be able to maintain trees between the databases but I am attempting to have each database own it's own independent tree structure.

The following code works as expected:
```python
database = 'default'

parent = Entity.objects.using(database).create()
child = Entity.objects.using(database).create()
child.parent = parent
child.save()
```

As does defining the entity with the parent during creation:
```python
database = 'default'

parent = Entity.objects.using(database).create()
child = Entity.objects.using(database).create(parent = parent)
```

--- 

However, as soon as the entity is not in the main database issues are encountered.
The first example now reads like this:
  ```python
database = 'anything-other-than-default'

parent = Entity.objects.using(database).create()
child = Entity.objects.using(database).create()
child.parent = parent
child.save()
```
This raises 
> mptt.exceptions.InvalidMove: A node may not be made a child of any of its descendants.

The second approach:
```python
database = 'anything-other-than-default'

parent = Entity.objects.using(database).create()
child = Entity.objects.using(database).create(parent = parent)
```
Raises the following:
```
  File "env/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "env/lib/python3.6/site-packages/mptt/models.py", line 1015, in save
    self.insert_at(parent, position='last-child', allow_existing_pk=True)
  File "env/lib/python3.6/site-packages/mptt/models.py", line 738, in insert_at
    refresh_target=refresh_target)
  File "env/lib/python3.6/site-packages/mptt/managers.py", line 72, in wrapped
    return method(self, *args, **kwargs)
  File "env/lib/python3.6/site-packages/mptt/managers.py", line 556, in insert_node
    target._mptt_refresh()
  File "env/lib/python3.6/site-packages/mptt/models.py", line 1057, in _mptt_refresh
    )[0]
  File "env/lib/python3.6/site-packages/django/db/models/query.py", line 289, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

If I go to line `env/lib/python3.6/site-packages/django/db/models/query.py` line 394 I can print out `self.db` and this points to `default` despite the all entities being created in a different database.

**Comment by DomHudson** [comment]
If I replace [this line](https://github.com/django-mptt/django-mptt/blob/master/mptt/models.py#L1044) with the following it seems to fix the issue:

```python
        values = manager.using(self._state.db).filter(pk=self.pk).values(
            opts.left_attr,
            opts.right_attr,
            opts.level_attr,
            opts.tree_id_attr,
        ).first()
```

**Comment by funkindy** [comment]
I have the similar issue. I have two different databases an i am unable to save anywhere instead of "default" database. 

not  <code>obj = Entity();
obj.save(using="non_default")</code>

 nor ```Entity().objects.using("non_default").create()``` works.

It always finds the default DB and tries to save there.
