### ISSUE TITLE
get_cached_trees - Utility Function appears to not cache parents correctly if passed multiple trees

### ISSUE THREAD

**Issue by Biskelion** [django-mptt/django-mptt#658]
https://github.com/django-mptt/django-mptt/blob/master/mptt/utils.py#L208

If you create a queryset with the nodes from 2 trees after you've iterated through the root node level 
 the next node found will have the previous node in the current path assigned as its parent even if it is from the second tree.

**Comment by artscoop** [comment]
This is still broken. This is the only way to get fast tree caching, but alas, it works incorrectly when there is more than one root node.
