### ISSUE TITLE
Multiple databases issue with rebuild()

### ISSUE THREAD

**Issue by funkindy** [django-mptt/django-mptt#686]
`rebuild()` method of tree manager doesnt work with the specific database.

`Entity.objects.db_manager("mydb").rebuild()` 

drops an exception trying to extract Entity from "default" database.

This is caused here: https://github.com/django-mptt/django-mptt/blob/b1cc0b4722d6410024a6c9282e5b3587ba9237d1/mptt/managers.py#L690

by the _default_manager (??)
This can be fixed by adding .db_manager(self.db) in chain after the _default_manager call.

**Comment by mgius** [comment]
Hi, I just ran into this bug as well.  It appears that the latest release does not include this fix.  Are there plans to cut a new release anytime soon?  I'm working around it but would love to not have to in the future.
