### ISSUE TITLE
verbose_name for django admin

### ISSUE THREAD

**Issue by jeyca** [django-mptt/django-mptt#695]
I tried to set `verbose_name` for a mptt field in django. When I used

`tree = models.ManyToManyField(Role, blank=True, verbose_name='Baum')`

the verbose name was not displayed  in the admin change page, of course because I modified the ObjectForm. So I tried to set `verbose_name` for 

`tree = mptt.TreeNodeMultipleChoiceField(queryset=Tree.objects.all(), verbose_name='Baum')`

but this throws an error because this argument does not exist, so is there a way to set a verbose_name for a mptt field?

**Comment by matthiask** [comment]
Form field labels are set as `label`, not as `verbose_name`. The choice field is a form field, not a model field.
