### ISSUE TITLE
ListFiltersTests fail with Django 2.1.5

### ISSUE THREAD

**Issue by vali-um** [django-mptt/django-mptt#696]
If run with django 2.1.5 the 3 ListFiltersTests fail for 2 reasons:

* django.contrib.admin.views.main.ChangeList.__init__() has an added required argument sortable_by
* the tests using request_factory requests require a user to be set, see https://docs.djangoproject.com/en/2.1/topics/testing/advanced/#example

If wanted i can provide a patch that fixes those issues for django2.1.5 but breaks the tests for django1.x

**Comment by vali-um** [comment]
i'm sorry i forgot to note:
this occurs in  django-mptt/tests/myapp/tests.py lines 2002-2212

**Comment by matthiask** [comment]
This should be fixed by 1ad9fb43421b5ab6a5dc3d04ed2e5100ff063882
