### ISSUE TITLE
How can I sort children by "create_time"?

### ISSUE THREAD

**Issue by huchunnuan** [django-mptt/django-mptt#703]
I have a comment model:
_class Comment(MPTTModel):
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children',
                            db_index=True)
    post = models.ForeignKey(to=Post, on_delete=models.CASCADE)
    content = models.TextFild( null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)_

I can sort level 0 comment by:
_Comment.objects.filter(post__pk=post_id, parent=None).order_by('-created_time')_
but I find the returned children comments are not sorted by create_time by calling get method, do you have solution?

**Comment by ChildMr** [comment]
我也想知道这个问题，求解答

**Comment by matthiask** [comment]
You could try using `order_insertion_by = "-created_time"` or something.

https://django-mptt.readthedocs.io/en/latest/search.html?q=order_insertion_by&check_keywords=yes&area=default

**Comment by ChildMr** [comment]
不，如果仅仅想让树倒叙排列， 则可以 order_by('-tree_id')
