### ISSUE TITLE
Bug in `is_child_node`

### ISSUE THREAD

**Issue by elcolie** [django-mptt/django-mptt#716]
`requirements.txt`
```
django==2.2.5
django-mptt==0.10.0
```
My tree has 65 nodes. Some of my leaf node has wrong attribute for example `#18`
![Pasted_Image_10_10_19_16_11](https://user-images.githubusercontent.com/18206728/66555299-a0546880-eb78-11e9-991e-e99e68b40aed.png)

```python
In [6]: q18 = Question.objects.get(id=18)

In [7]: q18.is_child_node()
Out[7]: True

In [8]: q18.is_leaf_node()
Out[8]: True

In [9]: q18.is_root_node()
Out[9]: False
```

**Expected Results:**
`q18.is_child_node()` must return `False`

**As is:**
It returns `True`

**Comment by matthiask** [comment]
Why would `is_child_node` return false when `First Name` is clearly a child of `Name(In English)`?

**Comment by elcolie** [comment]
My bad. Thank you it is `is` not `has`
