### ISSUE TITLE
Where are the **canonical** docs?

### ISSUE THREAD

**Issue by guettli** [django-mptt/django-mptt#729]
On this page there is a link " check out the docs": https://django-mptt.readthedocs.io/en/latest/tutorial.html

But this links points to github.io: http://django-mptt.github.io/django-mptt/overview.html

Where is the canonical place for the docs? readthedocs or github.io?

**Comment by rsmithlal** [comment]
Readthedocs is the up to date latest documentation. The github.io version is a couple versions out of date.

**Comment by matthiask** [comment]
I deleted the completely outdated `gh-pages` branch; a 404 is better than stale docs.

The readthedocs version should be up-to-date.

Thanks!

**Comment by rsmithlal** [comment]
@guettli where was the link that was pointing to the github pages url? When you say "this page", which page are you referring to?
