### ISSUE TITLE
Proper way to make soft-deletable MPTT models

### ISSUE THREAD

**Issue by lsnk** [django-mptt/django-mptt#745]
Hello.

I could not find such realization anywhere.

I want to make my MPTT model soft-deletable (via adding is_removed boolean field and filtering records with this flag out in model Manager get_queryset method).

I want to have 2 managers inside Model:
objects - TreeManager subclass in which I override get_queryset method to filter out records.
all_objects - old TreeManager without changes.

Some things work fine, but some things dont:

For example when I use **get_ancestors** / **get_descendants** / **get_children** model method I want to select records depending on if an object is removed or not. But they both use 'self._tree_manager' under the hood and I can't find easy way to override manager selection behavior.

Another problem is .children related manager also works strange.

The main question is, may be I missed something and there are project that provide such functionality? And if not, I need some guidance if things that I want can be achieved with MPTT?

Best Regards

**Comment by matthiask** [comment]
The behavior with soft-deleted leaf nodes is clear to me, but what should happen when soft-deleting nodes with descendants? Also, mptt does not prevent you from adding descendants to nodes which have already been soft-deleted.

Generally, django-mptt does not work well with filtered trees (for example `{% recursetree %}` does not like partial trees much). Some problems are inherent to incomplete trees, some are specific to django-mptt respectively the nested set model.

(I'm personally having a surprisingly good experience with recursive Common Table Expressions, for example with https://github.com/matthiask/django-tree-queries, but that really depends on your use case. It also does not answer the question what should happen when nodes are filtered away inside the tree structure.)

**Comment by lsnk** [comment]
I want behavior to be the same as original MPTT deletions (your just recoursively mark all the children removed as well). As for what I want to do with already deleted records and their methods I have not decided yet. That will be rare case for my project I guess so going this way seems counterproductive =) I guess I will look at my current solution and reevaluate it later.

**Comment by forgoty** [comment]
Hello @lsnk 

I`ve faced with similar task. Can you provide more information how you dealt with it on your project? What should I look for while dealing with soft delete in django-mptt?

**Comment by lsnk** [comment]
Hi @forgoty 

I've ended up with something like this (
    SoftDeletableQuerySetMixin and SoftDeletableModel classes are from django-model-utils package,
    TreeManager and TreeQuerySet classes are from MPTT
):

```
class SoftDeletableMPTTQuerySet(SoftDeletableQuerySetMixin, TreeQuerySet):

    def delete(self):
        self.get_descendants(include_self=True).update(is_removed=True)


class SoftDeletableMPTTManager(
    models.Manager.from_queryset(SoftDeletableMPTTQuerySet), TreeManager
):

    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(is_removed=False)


class SoftDeletableMPTTModel(SoftDeletableModel, MPTTModel):

    class Meta:
        abstract = True

    objects = SoftDeletableMPTTManager()
    all_objects = TreeManager()

    def delete(self, using=None, soft=True, *args, **kwargs):
        if soft:
            self.get_descendants(include_self=True).update(is_removed=True)
            self.refresh_from_db()
        else:
            return super().delete(using=using, *args, **kwargs)

    def get_ancestors(self, *args, **kwargs):
        if self.is_removed:
            return self._tree_manager.none()
        else:
            return super().get_ancestors(*args, **kwargs)
```

There're some problems with `all_objects` manager I beleive, but it works mostly fine.

**Comment by forgoty** [comment]
Thanks @lsnk for providing possible solution!

**Comment by coofercat** [comment]
I too was looking for something like this. I came up with this in my model class:
```
def get_children(self):
    qs = super().get_children()
    return qs.exclude(deleted_at__isnull=False)
```
(note: My `deleted_at` field is a nullable Datetime. null means "normal", a Datetime means "was deleted on this date".)

I _think_ this correctly removes soft deleted children from output (I'm not 100% sure I've covered all my use-cases yet, so may not have covered yours!). It's not the whole story, as you also need to remove soft deleted entries when you query the root of the tree as well, but you can do that in the queryset in your view or via 'Managers' in the model if you want.

My approach will definitely struggle if you want a hierarchical view of deleted items. If you can live without, then you can just do a regular query to get them all regardless of where they are in the hierarchy, so no `get_children` is required.

**Comment by matthiask** [comment]
There are more problems with soft deletion and MPTT by the way than I mentioned above.

You can calculate the number of child nodes by using only the `lft` and `rght` values of each node. If `rght = lft + 1` you know without additional queries that the node is a leaf. The code uses these properties here: https://github.com/django-mptt/django-mptt/blob/db95b7934173a6e493d21d049e141a66abeb83c0/mptt/models.py#L660-L668

With soft deleted models the assumption doesn't hold anymore.
