### ISSUE TITLE
Invalid field name

### ISSUE THREAD

**Issue by minyoung90** [django-mptt/django-mptt#748]
Hi,

I have these models,

```
class DocumentNode(mptt.MPTTModel):
    name = models.CharField(max_length=128, unique=True)
    parent = mptt.TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

class DocumentNodeVariable(models.Model):
    owner_node = mptt.TreeForeignKey(DocumentNode, on_delete=models.CASCADE, related_name='variables')
```

so, in a view,

`
queryset = DocumentNode.objects.select_related('variables').filter(id=pk)
`

then, I got this error,

**django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'variables'**

**Comment by matthiask** [comment]
Maybe you wanted `.prefetch_related("variables")`, not `select_related`?

**Comment by minyoung90** [comment]
Yes I didn't know 'select_related' can't dereference! Thanks!
