### ISSUE TITLE
JS Error with DraggableMPTTAdmin

### ISSUE THREAD

**Issue by chadsaun** [django-mptt/django-mptt#755]
I'm getting this Javascript error in the django admin.

```
draggable-admin.js:14 Uncaught TypeError: Cannot read property 'fn' of undefined
    at draggable-admin.js:14
```

I'm using Django v2.2

**Comment by adhoch** [comment]
I ran into the same problem, Django 2.2.3 and mptt 0.9.1. For some reason the draggable-admin script gets put before the jquery-init script.

To solve I added to my admin class:

`    class Media:
      js = (
        '/static/admin/js/jquery.init.js',
        '/static/mptt/draggable-admin.js')
`

`
class MainNavigationItemAdmin(DraggableMPTTAdmin):
    list_display = ('indented_title',)
    list_display_links = ('indented_title',)
    class Media:
      js = (
        '/static/admin/js/jquery.init.js',
        '/static/mptt/draggable-admin.js')
`

This duplicates the jquery init and the draggable admin.

**Comment by adhoch** [comment]
After further investigation it seems like I was sending the model in question through the view as context. When I stripped that out the order of js files corrected itself.

**Comment by chadsaun** [comment]
> After further investigation it seems like I was sending the model in question through the view as context. When I stripped that out the order of js files corrected itself.

So did you end up using the `class Media`? If not, what did you do to resolve it?

**Comment by adhoch** [comment]
Stripping the model from the view didn't consistently solved the problem.

I'll revert to using the class Media in the admin class until something better comes up.

**Comment by chadsaun** [comment]
Specifying the `js` property correctly in the `Media` class worked for me. Thank you 👍

Here is my usage with some more formatting:

```
@admin.register(MenuItem)
class MenuItemAdmin(MPTTMixin, DraggableMPTTAdmin):
    list_display = ['tree_actions', 'indented_title', 'link', 'is_active', 'open_in_new_tab', 'require_user_authenticated', 'require_no_user_authenticated']
    list_display_links = ['indented_title']
    mptt_indent_field = ['title']
    
    class Media:
        js = ('/static/admin/js/jquery.init.js', '/static/mptt/draggable-admin.js')
```

**Comment by matthiask** [comment]
Ah yes, that's definitely the right thing to do. Django 2.2 sorts the JS files so that dependencies are loaded first, but this also means that more dependencies have to be specified explicitly.

**Comment by chadsaun** [comment]
So, does that mean this happens to everyone who is using Django 2.2 or later? Or does it just happen to some?

**Comment by matthiask** [comment]
I think it happens to everyone using Django 2.2 or better.

**Comment by matthiask** [comment]
Oh, now I'm confused. This has been fixed a long time ago, in April 2019. Since then, django-mptt 0.10 AND 0.11 has been released. Are you running a (very) outdated version by chance?

**Comment by chadsaun** [comment]
I'm using version `0.9.1`

**Comment by matthiask** [comment]
Is there a reason why you're sticking with this outdated version? If not, I'd strongly advise you to upgrade.

**Comment by chadsaun** [comment]
I didn't realize that I wasn't on the latest version. I upgraded and it seems to work without any customization.
