### ISSUE TITLE
get_next_sibling() does not return the next adjacent sibling

### ISSUE THREAD

**Issue by minhtule** [django-mptt/django-mptt#765]
I have a simple tree like this
```
     A
-----|-----
|    |    | 
B    C    D
```
I checked their (left, right) tuple and they are correctly set: A (1, 8), B(2, 3), C(4, 5), D(6, 7).
When I call `get_next_sibling()` from B, I got D instead of C. It seems like [the code](https://github.com/django-mptt/django-mptt/blob/0.11.0/mptt/models.py#L648-L659) is missing `order_by` clause to guarantee the ordering. The `get_previous_sibling()` has [an `order_by` clause](https://github.com/django-mptt/django-mptt/blob/0.11.0/mptt/models.py#L685) so it's working as expected.

If this is indeed an issue, I would be happy to open a PR to fix it.

**Comment by goodtune** [comment]
My suggestion is to write a test case which demonstrates the bug and then make the change to resolve it.

It could be due to changed behaviour in the Django ORM over time, so be sure to check the results of the test case over all supported versions of Django.

**Comment by minhtule** [comment]
It would be quite hard to create a deterministic test because this bug also depends on the order returns by the underlying database (and also the data). For example, let's say we have a `Node` model and create 3 records: `Node(id=1)`, `Node(id=2)` and `Node(id=3)`. When we do a query `Node.object.all()` without any ordering, the database can return the nodes in any order e.g. 1, 3, 2 on my local machine and 1, 2, 3 on the CI machine.

**Comment by goodtune** [comment]
If you don't think you can create a deterministic test, how can you expect a deterministic result from the library?
