### ISSUE TITLE
RemovedInDjango40Warning

### ISSUE THREAD

**Issue by hanckmann** [django-mptt/django-mptt#777]
The library currently triggers the following warnings in my tests:

../usr/local/lib/python3.8/site-packages/mptt/signals.py:8
  /usr/local/lib/python3.8/site-packages/mptt/signals.py:8: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
    node_moved = ModelSignal(providing_args=[

If you need more info, I will be happy to help.

Thanks for building this awesome Django app!

**Comment by matthiask** [comment]
Thank you! Today's release of 0.12 fixes this problem.

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by matthiask** [comment]
Yes, thank you.
