### ISSUE TITLE
Filter tree queryset for nodes which are a descendant of another node?

### ISSUE THREAD

**Issue by bradydean** [django-mptt/django-mptt#806]
I have a tree queryset, and a gven list of nodes. I want to filter the queryset for nodes which are a descendant of at least one node in the give list of nodes. Is there a nice way to do this in one lookup?

At the moment I am collecting each node's descendants into one big query with `UNION`, then filtering the queryset for nodes only contained in that set.

**Comment by bradydean** [comment]
Thanks for the quick reply, I actually just found the `get_queryset_descendants` method and this does pretty much what I want. Once I have all of the descendants of my given list of nodes, I intersect that with the original queryset.

**Comment by bradydean** [comment]
@matthiask Actually I ended up using your code, it seems to work.

**Comment by matthiask** [comment]
Nice!
