### ISSUE TITLE
_get_level_indicator() with large level can eat up whole memory

### ISSUE THREAD

**Issue by PetrDlouhy** [django-mptt/django-mptt#814]
When `TreeNodeChoiceFieldMixin._get_level_indicator()` is called with MPTT `obj` with large `level` (like 963849161 which I got generated by `model_bakery`), the function can get extremely memory hungry and freezes the whole computer until it finally fails with:
```
terminated by signal SIGKILL (Forced quit)
```

I think, that the level needs to be limited to some sane number.
I also think it might be acceptable to raise an exception if the level is larger than limit, that would make debugging the problem easier.

**Comment by PetrDlouhy** [comment]
@matthiask I didn't created category 963 million levels deep. The `level` field just got planted to this value by `model_bakery`.

Using MPTT models created by bakery might be fixed by setting `default=1` to the `level` field.

But I think, that ensuring some sane limit in `_get_level_indicator()` might also help in some situation. It doesn't give sense to have indentation by more than e.g. 1000 characters anyways.

**Comment by matthiask** [comment]
Ah, alright. I'd definitely be fine with something like `min(100, level)` or even less – the widget will be unusable anyway.

**Comment by PetrDlouhy** [comment]
@matthiask Done in #818 with tests.
