### ISSUE TITLE
When I upgrade to version 0.15 i run into problem when the name of related is not "parent". Why not use opts.parent_attr?

### ISSUE THREAD

**Issue by henrikek** [django-mptt/django-mptt#829]
When I upgrade to version 0.15 i run into problem when the name of related is not "parent". Why not use opts.parent_attr?

_Originally posted by @henrikek in https://github.com/django-mptt/django-mptt/pull/820#discussion_r1340686478_

**Comment by matthiask** [comment]
Probably no good reasons, just buggy behavior.

**Comment by henrikek** [comment]
My idea was just to follow other structure in the code and not hardcode the name "parent" as other code sets the value dynamically according to "opt.parent_attr". For me, it's okay to close this issue.
