### ISSUE TITLE
Documenation on Readthedocs is not up to date

### ISSUE THREAD

**Issue by allburov** [django-mptt/django-mptt#838]
In the changelog you can see there's `0.14` version
https://django-mptt.readthedocs.io/en/latest/changelog.html

But there's `0.15` and `0.16` version as well!
https://github.com/django-mptt/django-mptt/blob/main/CHANGELOG.rst

May be some issue with credentials or authorization in RTD (idk how it works exactly).

**Comment by allburov** [comment]
I'd happy to help with that, but it likely requires access to ReadTheDocs!

Another way would be to publish it to GitHub Pages (even may be using RTD theme)

**Comment by matthiask** [comment]
Thanks for the report. I have fixed the integration and the documentation build itself.

> I'd happy to help with that, but it likely requires access to ReadTheDocs!

Yes, and also to the GitHub repository settings. I'm definitely willing to hand out the commit bit to people who show good jugdement and are willing to show up and do the work! See also https://github.com/django-mptt/django-mptt/issues/833

**Comment by allburov** [comment]
Wow, that's the speed, TY! :1st_place_medal:
