### ISSUE TITLE
AppRegistryNotReady in version 1.9.4

### ISSUE THREAD

**Issue by erny** [django-mptt/django-mptt#840]
* Problem: When I import a model inherited from MPTTModel from an app's __init__.py, I get a django.core.exceptions.AppRegistryNotReady exception.
* Django-mptt Version: 0.16.0
* Django: 4.x
* Minimal example to reproduce: Create a project and an app from scratch, add it to settings.INSTALLED_APPS, create a model which inherits from mptt.models.MPTTModel, and import this from the app's __init__,py file. (You can also import directly mptt.models from __init__.py without creating any class.)

I know that this is project is not maintained anymore, and the version of Django neither, but perhaps, I someone could me give an advice. 

The only way I was able to fix this was delaying models import until really needed (inside functions), although not very elegant, I have a lot of duplicated import lines.

It seems that django ORM is accessed during import of mptt.modes.MPTTModel.

My traceback (full file paths omitted):
<pre><code>
File "pp/mio/__init__.py", line 1, in <module>
    from .models import Clase3
  File "pp/mio/models.py", line 3, in <module>
    from mptt.models import MPTTModel, TreeForeignKey
  File "lib/python3.9/site-packages/mptt/models.py", line 437, in <module>
    class MPTTModel(models.Model, metaclass=MPTTModelBase):
  File "lib/python3.9/site-packages/mptt/models.py", line 287, in __new__
    cls = super_new(meta, class_name, bases, class_dict)
  File "lib/python3.9/site-packages/django/db/models/base.py", line 108, in __new__
    app_config = apps.get_containing_app_config(module)
  File "lib/python3.9/site-packages/django/apps/registry.py", line 253, in get_containing_app_config
    self.check_apps_ready()
  File "lib/python3.9/site-packages/django/apps/registry.py", line 136, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
</code></pre>

Thanks in advance.

**Comment by matthiask** [comment]
I have a website running Django 5.0.0 and django-mptt 0.16. It probably won't run for much longer, but for now everything is still working, so the problem isn't necessarily that django-mptt doesn't work with recent Django versions anymore. Maybe this comment isn't all that helpful for you, and I'm sorry if that's the case. I hope you find a solution for your project.

**Comment by erny** [comment]
I'm kind of embarrased because this error has nothing to do with django-mptt. The real problem is that in current versions of django (3.x, 4.x, 5.x) we're not allowed to import models during app startup before django hasn't loaded all models. I have a quite complex app and sometimes it's difficult to follow all imports.

Sorry. I close this issue.
